DataDog/lading

.github/workflows/ci.yml, .github/workflows/clippy.yml
=> adjust clippy workflow

src/file.rs, src/lib.rs
=> Add lines_written metric

Cargo.lock, lading_common/Cargo.toml, lading_common/src/payload/datadog_logs.rs
REF https://github.com/timberio/vector/pull/8441
=> Correct lading's Datadog payload

.github/workflows/release.yml
=> Add kafka_gen to release workflow

lading_common/src/payload/datadog_logs.rs
This commit gives the Datadog payload more intentional structure. Previously it
was very much the output of a fuzzing engine -- which lading basically has
embedded -- but this made any introspection on the payload quite challenging
needlessly.
=> Give Datadog payload more structure

Cargo.lock, lading_blackholes/Cargo.toml, lading_common/Cargo.toml, lading_generators/Cargo.toml
Signed-off-by: Toby Lawrence <toby@nuclearfurnace.com>
=> Open up 0.4.3 series

lading_generators/src/tcp_gen/worker.rs
This commit adjusts the tcp-gen to not break its worker loop when connecting to
the target doesn't work. We instead establish a fast loop to re-connect and
preserve the possibly expensive block cache as a result.
=> Don't destroy cache when TCP connection fails

Cargo.lock, lading_blackholes/Cargo.toml, lading_blackholes/src/bin/tcp_blackhole.rs
Need to ship TCP packets to the ether 👾
=> Add TCP blackhole

Dockerfile
Follow-up to https://github.com/blt/lading/pull/139.
=> Copy `tcp_blackhole` binary to Docker container

README.md, examples/lading.yaml, src/bin/lading.rs, src/captures.rs
=> Experiment with task killing as busy loop

Cargo.lock, Cargo.toml, src/blackhole/http.rs, src/blackhole/splunk_hec.rs, src/codec.rs, src/lib.rs
Best reviewed with whitespace changes ignored.
Signed-off-by: Jesse Szwedko <jesse.szwedko@gmail.com>
=> Add support for gzip decoding to blackholes

rust-toolchain.toml
Resolves https://github.com/blt/lading/pull/160#discussion_r849962917
=> Bump rust toolchain to 1.60

src/bin/lading.rs, src/generator.rs, src/inspector.rs, src/target.rs
This commit introduces startup ordering such that the target will start before
the inspector and the generator. The target PID is advertised to both of these
sub-servers and the inspector is fed the PID in its first argument.
Resolves #172
=> Introduce startup ordering, passing target PID to inspector

src/generator/tcp.rs
This commit addresses a shutdown bug in the TCP generator where, if the TCP
connection were long-lived, lading would not shut the generator down. This is
corrected by avoiding entering an infinite loop while the connection is held.
=> Address TCP generator shutdown bug

src/generator/http.rs, src/payload.rs, src/payload/apache_common.rs
This commit allows the HTTP generator to generate Apache Common lines.
=> Introduce Apache Common generation

.vscode/extensions.json, .vscode/settings.json
This pull request:
- adds a collection of recommended VSCode extensions for this project
- adds format-on-save hooks for Rust and TOML source files
The basic idea of this pull request is to make some minor ergonomic tweaks for editing source with VSCode.
n/a
n/a
=> Add Visual Studio Code project settings

README.md, src/block.rs
Two tiny docs fixes
Really just testing out PR workflow & commit signing
N/A
=> Minor docs fixes

.github/workflows/ci.yml
Runs the integration tests from #261 in CI.
Who doesn't love a good integration test!
=> Run integration tests in CI

.github/workflows/ci.yml, Cargo.lock, integration/README.md, integration/ducks/Cargo.toml, integration/ducks/src/main.rs, integration/shared/Cargo.toml, integration/shared/proto/integration_api.proto, integration/shared/src/lib.rs, integration/sheepdog/src/lib.rs, src/generator/tcp.rs
Add baseline support for TCP integration tests
This will allow more of the lading functionality to be tested
Followup to #261
=> TCP Integration Testing

integration/ducks/src/main.rs, integration/shared/src/lib.rs, src/block.rs
Fix some clippies that have arisen recently
=> chore: clippy fixes in tests

src/bin/lading.rs
Allow an empty string, trailing commas, and duplicate commas in key-value formatted command line values.
Improve our devex in scripts
Closes https://github.com/DataDog/lading/issues/302
N/A
=> Ignore empty KV pairs

CHANGELOG.md, Cargo.lock, Cargo.toml
Prepare a 0.10.0 release.
I'm following an informal release process that differs from previous releases. Here's what I plan to do:
- Preparation PR (this): update version & write the changelog
- After approval, merge to main and delete release branch (like usual)
- Tag release PR commit in main. This will kick off a github release and a semver-tagged container build.
We haven't had a release in a long time and we've made some recent breaking changes.
N/A
N/A
=> Prepare 0.10.0 release

CHANGELOG.md, Cargo.lock, Cargo.toml
Making a 0.10.1 release to fixup some pieces of the release automation.
Broken release workflow for 0.10.0
#327 
N/A
=> Prepare 0.10.1 release

CHANGELOG.md, Cargo.lock, Cargo.toml
More release workflow fixes.
Last release workflow still didn't work quite right.
#329 
N/A
=> Prepare 0.10.2 release

examples/lading.yaml, src/generator.rs, src/generator/file_tree.rs
Signed-off-by: Sylvain Afchain <sylvain.afchain@datadoghq.com>
Add a file tree generator. First the generator generates a tree, then it randomly generates file access and folder rename.
=> add a file tree generator

src/blackhole/http.rs
This PR adds support for arbitrary status codes and hardcoded string responses from the HTTP blackhole.
These capabilities allow us to mock a greater number of HTTP services.
N/A
N/A
=> HTTP blackhole: support arbitrary status codes & hardcoded string response body

CHANGELOG.md, Cargo.lock, Cargo.toml
Release #384 
N/A
N/A
I should have skipped the 0.10.4 release, but here we are.
=> Prepare 0.11.0 release

src/bin/lading.rs, src/target.rs
This makes lading exit with an error code if the target server returns an error.
A quiet failure was observed where the target binary didn't exist. Lading would run for the warmup duration and then exit with a success exit code. With this change, it will exit immediately with an error code.
SMP-274
N/A
=> Fail loudly if the target task fails

rust-toolchain.toml, src/blackhole/sqs.rs, src/generator/file_gen.rs, src/generator/grpc.rs, src/generator/kafka.rs, src/observer.rs, src/payload/apache_common.rs, src/payload/ascii.rs, src/payload/datadog_logs.rs, src/payload/foundationdb.rs, src/payload/json.rs, src/payload/splunk_hec.rs, src/payload/syslog.rs
Update to the latest Rust release. Fixes a discovered bug in the SQS blackhole.
🥬 
N/A
N/A
=> Update to Rust 1.66

src/blackhole.rs, src/blackhole/uds.rs, src/generator.rs, src/generator/uds.rs
This commit introduces a Unix Domain Socket (UDS) generator allowing lading to perform IPC over a socket. Likewise I have added a blackhole, allowing lading to be the target.
=> Introduce UDS generator and blackhole

CHANGELOG.md, Cargo.lock, Cargo.toml, examples/lading.yaml, src/bin/lading.rs, src/generator.rs, src/generator/process_tree.rs
This PR adds a process tree generator. The goal is to generate a process tree with variable width and height. The leaves execute a command line specified in the config file with static args/envs or generated ones. A typical "pstree like" gives : 
```
1994835  437791  |   |   |   |       \_ ./target/debug/lading --config-path ./examples/lading.yaml --target-pid 83568
1999492 1994835  |   |   |   |           \_ ./target/debug/lading --config-path ./examples/lading.yaml --target-pid 83568
1999545 1999492  |   |   |   |               \_ ./target/debug/lading --config-path ./examples/lading.yaml --target-pid 83568
1999914 1999545  |   |   |   |               |   \_ ./target/debug/lading --config-path ./examples/lading.yaml --target-pid 83568
1999547 1999492  |   |   |   |               \_ …
```
=> introduce process tree generator

src/generator/udp.rs
This commit brings the UDP generator into the same style as the TCP generator, removing an interior task. Shutdowns should now be more prompt and this change will also allow for memory backpressure -- see #445 -- to be implemented more naturally.
REF SMP-329
=> Convert UDP generator to `select!` model

src/generator/splunk_hec.rs
This commit is peer to #447, #448. I have not had to thread a `select!` through here as in the other commits but I did realize, following on from the file generator work, that we could make shutdown of sub-tasks a little more orderly. Considering that the splunk hec generator hangs lading shutdown sometimes this is a welcome adjustment.
REF SMP-329
=> Ensure splunk_hec spawned tasks obey shutdown

CHANGELOG.md
=> Release lading 0.12.0

src/config.rs, src/payload/opentelemetry_log.rs, src/payload/opentelemetry_metric.rs, src/payload/opentelemetry_trace.rs
This PR is semi-automatically generated by running `clippy --fix` on the project.
=> Address clippy complaints

src/generator/tcp.rs, src/generator/udp.rs, src/generator/unix_datagram.rs, src/generator/unix_stream.rs
Instrument the number of packets sent by generators where this is applicable.
Packets-per-second is an interesting performance view
N/A
N/A
=> Instrument packets sent

.github/workflows/regression.yml, .github/workflows/regression_trusted.yml, regression/Dockerfile, regression/cases/apache_common_http_both_directions_this_doesnt_make_sense/lading-target/lading.yaml, regression/cases/apache_common_http_both_directions_this_doesnt_make_sense/lading/lading.yaml, regression/cases/apache_common_http_to_blackhole/lading-target/lading.yaml, regression/cases/apache_common_http_to_blackhole/lading/lading.yaml, regression/cases/blackhole_from_apache_common_http/lading-target/lading.yaml, regression/cases/blackhole_from_apache_common_http/lading/lading.yaml, regression/metadata.source
Initial work to add the regression detector to this repo.
Detect regressions in `lading` and seek out any components with poor performance.
SMP-349
This won't run until it's merged to `main` due to the trusted/untrusted split.
=> Add regression detector workflow, two reasonable (?) experiments, and one unreasonable experiment

.github/workflows/regression_trusted.yml
The target command and args need to be quoted.
Get regression detector running in this repo
#514 #520
=> Quote lading target command

.github/workflows/regression_trusted.yml
A brief description of the change being made with this pull request.
=> Fix lading config extension

regression/cases/apache_common_http_to_blackhole/experiment.yaml
Use egress throughput to analyze the generator-less experiment. 
See if analysis passes with this in place.
#514
=> Analyze egress throughput for generator-less experiment

CHANGELOG.md, src/payload/common.rs, src/throttle.rs
A brief description of the change being made with this pull request.
=> Throttle fixes

Cargo.lock, Cargo.toml
Update the `metrics` family of crates
Staying up to date
#555 #556 #557
=> Update `metrics` crates

CHANGELOG.md, src/config.rs, src/generator/file_gen.rs, src/generator/file_tree.rs, src/generator/grpc.rs, src/generator/http.rs, src/generator/process_tree.rs, src/generator/splunk_hec.rs, src/generator/tcp.rs, src/generator/unix_datagram.rs, src/generator/unix_stream.rs, src/throttle.rs
This commit builds on https://github.com/DataDog/lading/pull/573, https://github.com/DataDog/lading/pull/574, https://github.com/DataDog/lading/pull/575 and threads the configuration of the
throttle through all of our generators. This commit finishes up our work
introducing new throttles into the project.
=>  Thread throttle configuration through project

CHANGELOG.md, Cargo.lock, Cargo.toml, src/blackhole.rs, src/blackhole/http.rs, src/blackhole/splunk_hec.rs, src/blackhole/sqs.rs, src/blackhole/tcp.rs, src/blackhole/udp.rs, src/blackhole/unix_datagram.rs, src/blackhole/unix_stream.rs, src/config.rs, src/generator.rs, src/generator/file_gen.rs, src/generator/grpc.rs, src/generator/http.rs, src/generator/splunk_hec.rs, src/generator/tcp.rs, src/generator/udp.rs, src/generator/unix_datagram.rs, src/generator/unix_stream.rs
Add optional component IDs to the top-level generator & blackhole config.
This will allow us to differentiate between components.
SMP-575
=> Component IDs

README.md
Adds a short description in the readme around how to control the logs that are visible on stdout.
I don't do a lot of Rust development and had to google for a bit before finding the answer, this may save future me a few minutes.
n/a
n/a
=> Adds instructions to enable logs during lading's operation

lading_capture/src/json.rs
This commit allows a json Line to be deserialized and also improves the public UI a touch. We also no longer support conversion of MetricKind from protobuf, a vestigial capability.
=> Update json Line representation slightly

lading/src/block.rs, lading/src/generator/file_gen.rs, lading/src/generator/grpc.rs, lading/src/generator/http.rs, lading/src/generator/splunk_hec.rs, lading/src/generator/tcp.rs, lading/src/generator/udp.rs, lading/src/generator/unix_datagram.rs, lading/src/generator/unix_stream.rs
This commit puts the block construction into a type, called `Cache`. We support a peek interface which requires mutable access and an indexing implementation which is read-only. This is not quite pleasing to the eye but it maintains the interfaces that already exist. This work is intended to be the basis of an infinite streaming `Cache`, not enabled by default. That work will be done in a follow-up PR.
For the most part this change is mechanical. The unix-datagram generator now follows the file-gen in sharing a single `Cache` instance per writer, rather than having one for each child.
REF SMP-664
=> Place block construction in a `Cache` struct

lading_payload/src/dogstatsd.rs
Useful for third-party projects utilizing the dogstatsd generator eg https://github.com/scottopell/dogstatsd-utils/
=> Implements default trait for new ValueConf

lading_payload/src/dogstatsd.rs
Adds constructors for these two dsd-generation components
Simpler usage in external projects https://github.com/scottopell/dogstatsd-utils
=> Adds constructors for metric and kind weights

CHANGELOG.md, Cargo.lock, lading/Cargo.toml
=> Prepare 0.20.0 release

Cargo.lock, lading/Cargo.toml, lading/src/observer/linux.rs
=> Update nix 0.26 -> 0.27

examples/dogstatsd-generation.yaml
Fixes the current example dogstatsd generator config file.
=> Updates dogstatsd example to match new format

CHANGELOG.md, Cargo.lock, lading/Cargo.toml, lading/src/bin/lading.rs, lading_payload/src/block.rs
This PR cuts lading 0.20.1, resolving runtime hangs present in 0.20.0 for most use caes.
REF SMPTNG-94
=> Lading 0.20.1

CHANGELOG.md, Cargo.lock, lading/Cargo.toml
Release 0.20.2 with #764, #765, #766, #767, #768.
[SMPTNG-4](https://datadoghq.atlassian.net/browse/SMPTNG-4)
[SMPTNG-4]: https://datadoghq.atlassian.net/browse/SMPTNG-4?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Prepare 0.20.2 release

CHANGELOG.md, lading/src/generator/tcp.rs
Found the same bug that was fixed in #778 in the tcp generator.
=> Fixes connection retry bug in TCP generator

Cargo.lock, Cargo.toml, lading/src/observer/linux.rs, lading_capture/Cargo.toml, lading_payload/src/trace_agent.rs, rust-toolchain.toml
This commit updates our toolchain and corrects and error where prost-build did not reference the workspace version.
=> Update toolchain, prost

integration/ducks/src/main.rs, integration/sheepdog/src/lib.rs, lading/src/bin/lading.rs, lading/src/captures.rs, lading/src/config.rs, lading/src/generator/http.rs, lading/src/generator/splunk_hec.rs, lading/src/generator/splunk_hec/acknowledgements.rs
Began the process of converting expects to the question mark operator
SMPTNG-114
=> Removing Expects from Lading

CHANGELOG.md
Adds changelog for 0.20.6-rc3
RC2 saw a bunch of force-pushes, wanted a clean RC.
=> Adds changelog for rc3

Cargo.lock, lading/Cargo.toml
Oversight from #793 , gotta change the actual RC version as well
=> Updates lading version to rc3

integration/shared/src/lib.rs, integration/sheepdog/src/lib.rs, lading/src/bin/lading.rs, lading/src/blackhole.rs, lading/src/blackhole/splunk_hec.rs, lading/src/blackhole/sqs.rs, lading/src/blackhole/tcp.rs, lading/src/blackhole/udp.rs, lading/src/blackhole/unix_datagram.rs, lading/src/blackhole/unix_stream.rs, lading/src/captures.rs, lading/src/generator/file_gen/logrotate.rs, lading/src/generator/file_gen/traditional.rs, lading/src/generator/grpc.rs, lading/src/generator/http.rs, lading/src/generator/splunk_hec.rs, lading/src/generator/tcp.rs, lading/src/generator/udp.rs, lading/src/generator/unix_datagram.rs, lading/src/generator/unix_stream.rs, lading/src/inspector.rs
=> Removed more expects from Lading

integration/sheepdog/src/lib.rs, lading/src/bin/captool.rs, lading/src/bin/lading.rs, lading/src/blackhole/sqs.rs, lading/src/captures.rs, lading/src/config.rs, lading/src/generator/file_gen/logrotate.rs, lading/src/generator/file_gen/traditional.rs, lading/src/generator/file_tree.rs, lading/src/generator/grpc.rs, lading/src/generator/http.rs, lading/src/generator/process_tree.rs, lading/src/generator/splunk_hec.rs, lading/src/generator/tcp.rs, lading/src/generator/udp.rs, lading/src/generator/unix_datagram.rs, lading/src/generator/unix_stream.rs, lading/src/inspector.rs, lading/src/lib.rs, lading/src/observer/memory.rs, lading/src/target.rs, lading/src/target_metrics/prometheus.rs, lading_payload/benches/dogstatsd.rs, lading_payload/src/block.rs, lading_payload/src/dogstatsd.rs, lading_payload/src/lib.rs, lading_throttle/src/lib.rs
Continued the process of converting expects to proper errors
=> Remove Expects

lading/src/blackhole/http.rs, lading/src/blackhole/splunk_hec.rs, lading/src/blackhole/sqs.rs, lading/src/captures.rs, lading/src/generator/process_tree.rs, lading/src/generator/splunk_hec.rs, lading/src/generator/splunk_hec/acknowledgements.rs, lading/src/generator/unix_stream.rs, lading_payload/src/block.rs, lading_payload/src/trace_agent.rs
This PR is a continuation of the effort to remove expects from Lading and convert them into errors we can propagate. 
Cleans up the overall code quality we are working with
SMPTNG-114
=> Removing More Expects from Lading

lading_payload/src/block.rs, lading_payload/src/dogstatsd.rs
The dogstatsd config had `default`s specified for every field. This can be accomplished by implementing `Default` for the struct and adding the `serde(default)` annotation to the struct.
Its now possible to get a "default" config via code, rather than only being able to do it via a serde-deserialization.
I also fixed up the `valid` function to return something useful to the user and propagate this error up so its visible to the user.
Before this you would simply have an error such as:
```
Error: LadingGenerator(UnixDatagram(Block(InvalidConfig)))
```
Now that should both print a `warn` and include the invalid-reason string in the final error message.
=> Switches dogstatsd config to use default trait instead of serde default

.github/workflows/release.yml
Added a comment about cc behavior regarding the CFLAGS and the CXXFLAGS
=> Added a comment about cc behavior regarding the CFLAGS and the CXXFLAGS

lading/src/bin/payloadtool.rs
This removes the custom "get_blocks" implementation inside of `payloadtool` in favor of the standardized option in `block`
payloadtool should match lading as closely as possible.
=> Convert payloadtool to re-use the same block size config as main lading

.github/workflows/container.yml, amd64.Dockerfile, arm64.Dockerfile
This commit attempts to build lading on amd64 and arm64. I will also attempt improvements in build speed. Note we now only build the lading binary when building containers.
REF SMPTNG-151
=> Improve lading container builds

.github/actions/install-protobuf/action.yml, .github/workflows/ci.yml
Rust-toolchain-related CI errors.
=> Refactor gh actions

deny.toml, rust-toolchain.toml
Removes some entries from `deny.toml`
Fix CI for `cargo-deny`
=> Attempt to fix cargo-deny CI failure

lading/Cargo.toml
Fair to say that Scott's got as much to do with lading's internals as me and George at this point. Adding him to the authors list.
=> Add Scott to the authors list, fix a syntax issue with George

.github/workflows/release.yml, CHANGELOG.md, Cargo.toml, Cross.toml
Adds two new targets to the build script.
Some target images are musl libc based (alpine)
=> Adds musl libc based builds

CHANGELOG.md, lading_payload/src/dogstatsd.rs
=> Increases context limit for dsd payloads

Cargo.lock, lading/Cargo.toml, lading/src/target_metrics/prometheus.rs
Adds tests to ensure our target metric scraper works as intended.
In the future, I'd like to swap in https://github.com/sinkingpoint/openmetrics-parser or similar to ensure full compliance with all openmetrics endpoints.
=> Adds tests for target metric scraping

Cargo.lock, lading/Cargo.toml, lading/src/bin/captool.rs
Extracts the capture file before processing if needed.
=> Adds zstd support to lading captool

integration/ducks/src/main.rs, integration/sheepdog/src/lib.rs
Fix integration test issues seen in https://github.com/DataDog/lading/pull/877
=> Integration test fixes

lading_payload/src/block.rs
In practice we treated any non-Some return from the function `construct_block` as a signal that the block construction needed to be retried: the setup was not satisfiable. The original motivation for this return type was based on a slow drift of my thinking and that drift is now complete.
Important to tidy up #886
=> Remove optional return of construct_block

CHANGELOG.md, Cargo.lock, lading/Cargo.toml
This commit releases lading 0.21.0. Please see changelog for details.
=> Release lading 0.21.0

examples/dogstatsd-generation.yaml
Fixes the example dogstatsd config.
=> Updates dsd lading example to accommodate block size changes

CHANGELOG.md, Cargo.lock, lading/Cargo.toml
=> Cuts lading 0.21.1

Cargo.lock, Cargo.toml, lading/Cargo.toml, lading/src/bin/lading.rs, lading/src/blackhole/http.rs, lading/src/blackhole/splunk_hec.rs, lading/src/blackhole/sqs.rs, lading/src/blackhole/tcp.rs, lading/src/blackhole/udp.rs, lading/src/blackhole/unix_datagram.rs, lading/src/blackhole/unix_stream.rs, lading/src/captures.rs, lading/src/generator/file_gen/logrotate.rs, lading/src/generator/file_gen/traditional.rs, lading/src/generator/grpc.rs, lading/src/generator/http.rs, lading/src/generator/passthru_file.rs, lading/src/generator/splunk_hec.rs, lading/src/generator/splunk_hec/acknowledgements.rs, lading/src/generator/tcp.rs, lading/src/generator/udp.rs, lading/src/generator/unix_datagram.rs, lading/src/generator/unix_stream.rs, lading/src/observer/linux.rs, lading/src/target.rs, lading/src/target_metrics/expvar.rs, lading/src/target_metrics/prometheus.rs
This commit updates our use of the metrics-rs crate to latest, putting us in position to make use of upstream features in the near-term.
=> Update metrics-rs crate

CHANGELOG.md, Cargo.lock, lading/Cargo.toml, lading/src/bin/lading.rs
When I implemented this in #906 I was working in a stack and completely lost track of exposing this new work in the CLI: there was no way to flip this feature on. Fixed in this PR.
=> Expose target container targetting

lading_signal/src/lib.rs
Add peer count to `signal_and_wait` logs.
Improve visibility into incorrect behavior.
Written in pairing with @blt.
=> Log peer count when waiting for signal

CHANGELOG.md, Dockerfile, lading_signal/Cargo.toml, lading_throttle/Cargo.toml, rust-toolchain.toml
This commit updates the rust toolchain in lading project to latest stable.
=> Update rust toolchain to 1.81.0

lading_signal/src/lib.rs
This commit allows for `Watcher` instances to be created that are not
registered and will not block `signal_and_wait`.
REF SMPTNG-455
=> Allow for unregistered watchers

Cargo.lock, integration/ducks/Cargo.toml, lading/Cargo.toml
This reverts PR #991. Once_cell 1.20.0 is yanked.
=> Revert "Bump once_cell from 1.19.0 to 1.20.0 (#991)"

lading/src/bin/captool.rs, lading_capture/src/json.rs
Add a captool flag to dump a series' values.
View captures in detail for debugging.
=> captool: add series value dumping capability

CHANGELOG.md, Cargo.lock, lading/Cargo.toml
Prepare release 0.23.2.
Deploy fixes: #987, #980, #970, #998
=> Prepare release 0.23.2

Cargo.lock
This commit runs a simple `cargo update` on the project. There are a handful of top-level dependencies that remain out of data -- tonic, tower, hyper, http being the most difficult -- but this commit picks up a small host of updates.
=> Run `cargo update` on the project

integration/ducks/src/main.rs, integration/sheepdog/src/lib.rs, lading/src/bin/captool.rs, lading/src/bin/lading.rs
This makes some stylistic changes to the codebase.
This should improve readability and maintainability
=> style: simplify string formatting for readability

Cargo.lock, lading/Cargo.toml, lading/src/bin/logrotate_fs.rs, lading/src/generator/file_gen/model.rs
This commit finally adds rotation to the model. I have not tested it yet but the thing compiles and that's worth preserving. Subsequent commits will get it working.
=> Rotate log files

CHANGELOG.md, Cargo.lock, lading/Cargo.toml
This release modifies the logrotate FS configuration to include a load profile, allowing the user to specify either constant load for a linearly increasing load. This is a breaking configuration change.
REF SMPTNG-517
=> Release lading 0.24.0

deny.toml
=> cargo-deny ding on an OSI license

Cargo.lock, lading/Cargo.toml
This commit updates the bollard create. I've had to add more feature
flags to allow necessary functions into the build, but otherwise
this is a simple version bump.
=> Update bollard crate

CHANGELOG.md, lading/src/blackhole/http.rs
This reverts commit 7df73bce1f9c8aa9665da37184208bcfa0c9b4ff.
=> Revert "Adds path to metric labels for http blackhole (#1148)"

Cargo.lock, Cargo.toml, integration/sheepdog/Cargo.toml
This commit updates the tower crate from 0.4 to 0.5.
=> Update `tower` to 0.5

Cargo.lock, lading/Cargo.toml, lading/src/blackhole/http.rs, lading/src/blackhole/splunk_hec.rs, lading/src/blackhole/sqs.rs, lading/src/codec.rs, lading/src/generator/http.rs, lading/src/generator/splunk_hec.rs, lading/src/generator/splunk_hec/acknowledgements.rs, lading/src/lib.rs
This commit begins the hyper upgrade in lading/ itself. This will be a
slow process spread over many commits.
=> Begin hyper upgrade in lading/

CHANGELOG.md, lading/src/observer/linux/procfs/memory/smaps.rs
Corrects the mistaken changelog modifications from #1231 and #1237
=> Corrects last two changelog entries

lading/src/observer/linux/procfs.rs
We are guaranteed that pids are unique once the skipped set is
being interrogated, so we avoid creating a set and maintain a counter
only.
=> Counts for skipped processes, not a set

.github/workflows/ci.yml
This commit is intended to fix a current CI break with the nextest install being rejected with a 403.
=> This commit fixes the nextest install in CI

CHANGELOG.md, lading/src/bin/lading.rs
Removes an unused cli subcommand.
[YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)
=> Removes process tree generation subcommand

CHANGELOG.md, Cargo.lock, lading/Cargo.toml
Prepare to release version 0.27.0.
=> Prepare 0.27.0 release

.github/workflows/config-validation.yml, examples/lading-logrotatefs.yaml
Adds a CI check to ensure all configs in the `./configs` folder properly pass validation (aka, deserialize properly)
yaml is hard to write (correctly)
=> Validate example configurations as part of CI

Cargo.lock, lading/src/generator/file_gen/logrotate_fs.rs, lading_payload/fuzz/Cargo.lock, lading_payload/fuzz/Cargo.toml, lading_payload/fuzz/fuzz_targets/fixed_cache_creation.rs, lading_payload/fuzz/fuzz_targets/fixed_cache_creation_apache_common.rs, lading_payload/fuzz/fuzz_targets/fixed_cache_creation_ascii.rs, lading_payload/fuzz/fuzz_targets/fixed_cache_creation_datadog_log.rs, lading_payload/fuzz/fuzz_targets/fixed_cache_creation_dogstatsd.rs, lading_payload/fuzz/fuzz_targets/fixed_cache_creation_fluent.rs, lading_payload/fuzz/fuzz_targets/fixed_cache_creation_json.rs
This commit updates our fuzz tests to the point where they are functional. I have not
not otherwise made changes that are not mechanically motivated.
=> Update lading_payload fuzz tests to functional state

lading/src/generator/http.rs, lading_payload/src/block.rs
This commit introduces a new `Handle` API into the block cache,
inspired by the approach we took in logrotate_fs but with the goal of
being generally usable. I have only converted the HTTP generator to
demonstrate the utility of this approach in a generator with multiple
parallel connections. My intention is to convert TCP generator after
this, then all generators in a single PR. This last PR will remove the
old non-Handle API.
=> Introduce `Handle` interface to block cache, avoid duplication in HTTP generator

lading/src/generator/tcp.rs
This commit adjusts the tcp generator use the new `Handle` approach,
demonstrating that for single-task generators this approach is a
simple mechanical change.
=> Convert tcp generator to block cache `Handle` approach

lading/src/generator/common.rs, lading/src/generator/http.rs, lading/src/generator/tcp.rs, lading/src/generator/udp.rs
We have a few well-established patterns for generators now and this
commit is an attempt to trim down on the duplication.
=> Unify configuration for generators

Cargo.lock, lading/Cargo.toml
This commit updates our k8s dependencies, closing #1514, #1512 and #1510.
=> Update kubernetes dependencies
