src/file.rs

Internal to file_gen's LogTarget is the notion of bytes_written, which is what
tracks progress toward the maximum file size of the target. Also there is a
bytes_written that is output as telemetry which really tracks the bytes filled
into the buffer, not the global size. Unfortunately because of name confusion I
got the whole mess confused and it looked like, from telemetry, that byte output
rate was getting faster and faster. Provably not accurate by looking at the
file.
Closes #4

Correct "bytes_written" telemetry

---

.github/workflows/bloat.yml

This commit disables cargo-bloat from being run on pull requests as doing so
never quite works for dependabot, for reasons I do not understand. Works fine
otherwise, which is primarily where I want it.

Disable cargo-bloat on pull requests

---

Cargo.lock
Cargo.toml
src/file.rs

I worked quite hard yesterday on the previous commit and convinced myself of a
non-thing. This resulted in there being no logs written to disk.

Fix file writing

---

Cargo.lock
Cargo.toml
src/file.rs
src/payload/ascii.rs
src/payload/json.rs

This commit breaks up the block building into iterators so that we can bring
rayon to bear in their construction. This significantly reduces startup time.

Use rayon to push faster byte block builds

---

Cargo.lock
Cargo.toml
src/file.rs
src/payload/ascii.rs
src/payload/json.rs

This commit ensures that the data we generate from Ascii and Json has a definite
size to it, primarily by selecting from a fixed array of sizes. This is... a
little less arbitrary than I would have liked but it's better than a file full
of blank lines.

Make generated data less blank

---

Cargo.lock
Cargo.toml
src/file.rs
src/main.rs
src/payload/ascii.rs

We have discovered situations where file_gen runs out of disk space and then
quietly stop. This happens when testing vector once vector falls behind.

Crash when a worker crashes

---

src/config.rs
src/file.rs
src/payload.rs
src/payload/foundationdb.rs

This commit adds a limited ability to generate FoundationDB logs. There's more
variants to be added and any fields in the existing variants that have an
internal complex structure have been dropped.

Add the ability to generate limited FoundationDB logs

---

Cargo.lock
Cargo.toml
src/file.rs
src/payload/foundationdb.rs

This commit addresses important mistakes in the FoundationDB generator. Firstly,
the size of the serialized FoundationDB json lines will cause some block sizes
to exceed the maximum bytes per second, a problem. Second, the names of fields
were not correct. Numbers are now quoted as in the FDB logs.

Correct FoundationDB building

---

Cargo.lock
src/bin/file_gen.rs
src/block.rs
src/file.rs
src/lib.rs
src/payload.rs
src/payload/ascii.rs
src/payload/foundationdb.rs
src/payload/json.rs
src/payload/statik.rs

Previously it was possible for file_gen to crash when generating new blocks as a
result of those blocks outpacing the governor. To resolve this I've hidden the
Arbitrary definition behind a slightly reworked Serializer trait. The caller is
now responsible for setting up instances of Serializer and nothing more.
Startup is now slower, unfortunately, because the Serializer isn't Sync + Send
necessarily, but that couldn't be helped.
Resolves #45. 

Fix malformed block creation

---

src/config.rs
src/file.rs
src/payload.rs
src/payload/common.rs
src/payload/datadog_logs.rs

It's now possible for this program to generate Datadog agent's log
payloads. This is in preparation for an HTTP generator in a similar manner to
file_gen, implying that this repo is increasingly misnamed and misdocumented.

Add the ability to generate Datadog Log payloads

---

Cargo.lock
lading_common/Cargo.toml
lading_common/src/payload/datadog_logs.rs
udp_blackhole/Cargo.toml

After discussion in https://github.com/timberio/vector/pull/8297 I've realized
that the logs payload here was too meager, not reflective of the actual datadog
logs agent. This commit addresses that.

Expand the Datadog logs payload

---

Cargo.lock
Cargo.toml
blackhole/Cargo.toml
blackhole/README.md
blackhole/src/bin/http_blackhole.rs
blackhole/src/bin/udp_blackhole.rs
udp_blackhole/README.md

This commit introduces a new program, `http_blackhole`. It is what it sounds
like, a spot for HTTP traffic to sink into. It only ever responds 200 OK to all
traffic with a blank body when that's relevant. I have moved all the blackhole
programs into a single crate and have a notion we might do the same with
generation.

Introduce `http_blackhole`

---

Cargo.lock
lading_blackholes/Cargo.toml
lading_blackholes/src/bin/http_blackhole.rs
lading_generators/Cargo.toml
lading_generators/src/http_gen/worker.rs

This commit improves the http blackhole. It enables http2 upgrades and avoids
using CONTENT_LENGTH header, insteady relying on the length of the observed
body. This solves the problem of unreliable clients setting the wrong length and
also avoids issues where hyper server hangs up too quickly on a client still
sending a body.

Improve `http_blackhole`

---

Cargo.lock
lading_generators/Cargo.toml
lading_generators/src/bin/kafka_gen.rs
lading_generators/src/kafka_gen.rs
lading_generators/src/kafka_gen/config.rs
lading_generators/src/kafka_gen/worker.rs
lading_generators/src/lib.rs

Closes #65 
Introduces a new generator -- `kafka_gen` -- which produces messages to Kafka.  This first cut does not address any sort of parallelization of producers, since we should be able to hit modest throughput rates even with a single producer task.
We've added support to precache blocks, can generate all of the existing data variants, etc etc, and allow for multiple producer targets, similar to `http_gen`, which maps, essentially, to a specific Kafka server (cluster, really) and topic combination.

Introduce a new generator: kafka

---

lading_common/src/payload/datadog_logs.rs
lading_generators/src/kafka_gen/worker.rs

Currently, the worker code for `kafka_gen` does a synchronous send loop: send a request, wait for `rdkafka` to take it and send it, and then loop back around.  This is slow.  We can do like 3-4MB/second this way, tops, per thread.
Now, instead, we perform a core loop of sending messages, without awaiting their actual send to the cluster, until `rdkafka`'s internal send queue is full.  Once that happens, we try and drive any of the delivery futures to completion before looping back around and saturating the send queue once again.  In this way, we can easily send 400 to 500MB/second with a single task, which should be more than enough for any Vector soak tests we wish to run.

Speed up kafka_gen maximum throughput by batching.

---

.github/workflows/release.yml
Cargo.lock
Cargo.toml
lading_blackholes/Cargo.toml
lading_blackholes/src/bin/http_blackhole.rs
lading_common/Cargo.toml
lading_common/src/payload.rs
lading_common/src/payload/datadog_logs.rs
lading_common/src/payload/fluent.rs
lading_generators/src/bin/tcp_gen.rs
lading_generators/src/http_gen/worker.rs
lading_generators/src/lib.rs
lading_generators/src/tcp_gen.rs
lading_generators/src/tcp_gen/config.rs
lading_generators/src/tcp_gen/worker.rs

This PR introduces a new generator for TCP and a new payload, fluent. The TCP generator at present only supports fluent payloads, though this is easy to modify in the future if we desire. I have not included the wide-open bytes-per-second configuration option that `kafka_gen` has, though I think we probably do want to spread that across all the generators. As with `http_gen` the `tcp_gen` will keep pace with its target and unlike `http_gen` only has a single connection at present.

Introduce `tcp_gen`, fluent payload

---

Cargo.lock
lading_common/Cargo.toml
lading_common/src/payload.rs
lading_common/src/payload/syslog.rs
lading_generators/src/tcp_gen/config.rs
lading_generators/src/tcp_gen/worker.rs

This PR gives lading the ability to generate Syslog5424 from tcp_gen. I have confirmed this is parsed by vector.

Generate Syslog5424

---

lading_generators/src/file_gen/config.rs
lading_generators/src/file_gen/worker.rs
lading_generators/src/http_gen/config.rs
lading_generators/src/http_gen/worker.rs
lading_generators/src/kafka_gen/config.rs
lading_generators/src/kafka_gen/worker.rs
lading_generators/src/tcp_gen/config.rs
lading_generators/src/tcp_gen/worker.rs

This commit allows the user to set block sizes for generators. This does not
allow them to adjust individual message sizes -- unless a block is equivalent to
a message -- but does allow indirect control. Essentially, the larger the block
the larger the message for some formats.
This is mostly useful for systems that have a hard cap on the total payload size
-- say, UDP when we get to that -- or in situations where we need to simulate
consistent producers a little more carefully.

Allow user to set block sizes

---

lading_common/src/payload.rs
lading_common/src/payload/splunk_hec.rs
lading_generators/src/http_gen/config.rs
lading_generators/src/http_gen/worker.rs

This commit adds the ability to generate splunk's hec payload format. Time
doesn't vary presently, which is a little weird, but that seems like it's easy
to resolve if we ever need.

Add splunk_hec payload

---

.dockerignore
.github/workflows/release.yml
Dockerfile

Signed-off-by: Spencer Gilbert <spencer.gilbert@gmail.com>
I think this release process should work, based off the gh docs and actions examples. I didn't see that any of the lading tools needed any system deps aside from libc things

Add basic Dockerfile and image release job

---

Cargo.lock
lading_blackholes/Cargo.toml
lading_blackholes/src/bin/http_blackhole.rs
lading_blackholes/src/bin/udp_blackhole.rs
lading_common/Cargo.toml
lading_generators/Cargo.toml
lading_generators/src/bin/file_gen.rs
lading_generators/src/bin/http_gen.rs
lading_generators/src/bin/kafka_gen.rs
lading_generators/src/bin/tcp_gen.rs

Previously we allowed for some lading programs to be configured through
command-line flags. This makes lading challenging to use in contexts where
file-based configuration is more convenient, so we now have every lading binary
read a config file from under `/etc/lading`.

Configure all lading programs through files

---

.github/workflows/release.yml
Cargo.lock
lading_blackholes/Cargo.toml
lading_blackholes/src/bin/splunk_hec_blackhole.rs
lading_common/Cargo.toml
lading_generators/Cargo.toml

This PR adds a simple Splunk HEC blackhole that handles the following Splunk HEC paths
- POST `/services/collector/event | /services/collector/event/1.0 | /services/collector/raw | /services/collector/raw/1.0`
```jsonc
// Example response
{
text: "Success",
code: 0,
ackId: 0,
}
```
`ackId` is a global `AtomicU64` that increments after each request, wrapping to 0 if needed. For simplicity, there is no notion of Splunk channels in this blackhole, but clients using channels can still successfully interact with this server. There is no Splunk HEC protocol guarantee that each channel receives `ackId`'s starting from `0`. 
- POST `/services/collector/ack`
```jsonc
// Example response
{
acks: {
0: true,
1: true,
}
}
```
For any ack query, we map over the provided `ackId`'s and return true.
- …

Add Splunk HEC blackhole

---

lading_generators/src/http_gen/worker.rs

This commit grants http_gen the ability to use it's static config option,
previously available but in a crash-your-program way.

Allow http_gen to use static file payloads

---

.github/workflows/release.yml
Dockerfile

This commit allows the release workflow to run for any push, tagging with SHA
and tag when available. This allows us to experiment with in-flight lading
changes without cutting a full release.

Allow release workflow to run for any push

---

lading_generators/src/tcp_gen/worker.rs
rust-toolchain.toml

This commit makes tcp_gen mirror http_gen with regard to write errors. The panic
on failed write approach makes sense when we're in a test rig, less when the
program is supposed to be generally useful.

Make tcp_gen less crash prone around write errors

---

src/blackhole.rs
src/blackhole/http.rs
src/blackhole/splunk_hec.rs
src/blackhole/sqs.rs
src/blackhole/tcp.rs
src/blackhole/udp.rs
src/captures.rs
src/common.rs
src/config.rs
src/generator.rs
src/generator/file_gen.rs
src/generator/http.rs
src/generator/kafka.rs
src/generator/splunk_hec.rs
src/generator/tcp.rs
src/inspector.rs
src/lib.rs
src/signals.rs
src/target.rs

This commit requires that all public exports of the lading crate be
documented. What is here now is at least an okay first-pass but the README needs
to be properly updated to explain how the project works, is meant to be used
etc.

Set missing_docs deny

---

.github/workflows/release.yml

The use of QEMU makes the release build on ARM ruinously slow. Also, recently,
mysteriously, the jobs have been failing with a KILLED message. Absent any
further information I'm at least interested in getting the ARM build to fail
faster.

Avoid qemu emulation in release build

---

src/bin/lading.rs
src/inspector.rs

This commit passes the target pid as TARGET_PID to the inspector. This was
easier to deal with than an argument, as it allows the called program to do
whatever they like in terms of arguments.

Pass target pid as environment variable TARGET_PID

---

Cargo.lock
Cargo.toml
src/bin/lading.rs
src/config.rs
src/lib.rs
src/observer.rs

This commit introduces procfs dependency to the project and uses it to power an
'observer' server that runs as a peer to the target etc. This observer is
responsible for periodically reading the /proc/PID/stat of the target process,
writing out interesting details regarding memory consumption, CPU and scheduling
time. In this commit we collect:
* page_size -- the memory page size of the OS in bytes
* ticks_per_second -- the OS ticks that happen in a second
* rss_pages -- the real memory pages the process has allocated
* rsslim_bytes -- the soft limit of RSS in bytes
* num_threads -- the number of threads the process has running
* utime_ticks -- the number of ticks the process has spent scheduled in user-space
* stime_ticks -- the number of ticks the process has spent scheduled in …

Collect CPU, memory, scheduling information about the target process

---

src/captures.rs
src/observer.rs

The gauge! macro from metrics requires an f64 but stores as an atomicu64. Our
collector failed to coerce this value properly, resulting in some hilariously
large gauges. I also realized that I could use serde's 'untagged' enum
representation to avoid casting floats to u64, saving some decimals if any
gauges are actually f64s.

Correct gauge collection

---

Cargo.toml
src/bin/lading.rs
src/blackhole/http.rs
src/generator/tcp.rs
src/payload/statik.rs

This commit modifies the static generator to take either a file or a
directory. The block sizes are used as filters now, meaning we no longer assume
files can be arbitrarily truncated on line boundaries and instead pass the whole
file forward if `max_bytes` is sufficient to do so. It is up to the preparer of
static data to guarantee sufficient entropy.

Allow static payload to take a directory

---

src/generator/file_gen.rs

Previously the file generator would write to the end of its file, delete the
file and then start over with the same name. This caused some tailing programs
to perform strangely. That said, it's not necessarily interesting to _always_
remove handles and in some cases users would like to experiment with the tailer
doing file removal.
This is now possible. File generator will now always increment the file index
whether rotation is on or not but does allow the user to decide if rotation
happens, which it does by default.

Allow file_gen users to decide on rotation

---

src/bin/lading.rs
src/config.rs

This commit allows the user to configure lading to have multiple generators and
blackholes, enabling more complex testing of targets. Vector project is expected
to make good use of this capability.
No guarantees are made about ordering at startup and shutdown, except those that
already exist.
Resolves #227

Support multiple generators and blackholes

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yml
CONTRIBUTING.md
LICENSE
LICENSE-3rdparty.sh
NOTICE
README.md
deny.toml

I originally started lading as a side project, a little hack to write up for
technical writing purposes but found that it proved useful in my work on the
Vector project. Over time lading has got more and more useful to me and it's
more and more awkward to have it under my personal user.

Prepare lading for move under Datadog org.

---

Dockerfile

This commit updates the Dockerfile in the Lading project to use
an image that includes Rust 1.62.1 instead of Rust 1.58.0. 
Lading's toolchain also uses Rust 1.62.1, which motivates updating the Dockerfile. Changes were taken from Dockerfiles in https://github.com/DataDog/single-machine-performance.
n/a
n/a

Dockerfile: update to use Rust 1.62.1

---

Cargo.lock
Cargo.toml
src/captures.rs

Group update of the three metrics crates we use. Pulls in: #258, #259, #252.
`metrics` and `metrics-utils` need to be updated in lockstep, at least for these versions. TBD if this is always the case. I'll ask Toby about that when we chat.

Update metrics crates

---

Dockerfile
rust-toolchain.toml

This commit bumps our Rust version to track stable. No user-observable changes
to lading are intended or expected.

Bump Rust from 1.62.1 to 1.63.0

---

Cargo.lock
integration/ducks/Cargo.toml

These are unused. Saves build time & dependabot pings.
These crates are not used here. Delete them to save build time & dependabot pings.

Delete aws crates from ducks

---

Cargo.lock

It looks like we're having some issues with `nix` trying to move backwards in the lockfile on `main`. This is causing CI failures in dependabot PRs. This PR updates everything at once and should get us to a place where incoming PRs will pass CI.
I haven't dug into why nix is being downgraded, but I verified that we're not using a yanked version or anything.
Get dependabot back to a nice state.
Updating crates.io index
Updating anyhow v1.0.61 -> v1.0.62
Updating axum v0.5.13 -> v0.5.15
Updating bumpalo v3.10.0 -> v3.11.0
Updating clap v3.2.16 -> v3.2.17
Updating clap_derive v3.2.15 -> v3.2.17
Updating either v1.7.0 -> v1.8.0
Updating futures v0.3.21 -> v0.3.23
Updating futures-channel v0.3.21 -> v0.3.23
Updating futures-core v0.3.21 -> v0.3.23
Updating futures-executor v0.3.21 -> v0.3.23 …

Full cargo update

---

Cargo.lock
integration/sheepdog/Cargo.toml

Remove the `tokio-process` dependency. Turns out it wasn't necessary - it's an old crate left over from when tokio used many separate crates.
This should close our dependabot security advisories.

Remove `tokio-process` & fix dependabot security advisories

---

Cargo.lock
Cargo.toml
src/block.rs
src/generator/file_gen.rs
src/generator/http.rs
src/generator/kafka.rs
src/generator/splunk_hec.rs
src/generator/tcp.rs
src/payload.rs
src/payload/apache_common.rs
src/payload/ascii.rs
src/payload/datadog_logs.rs
src/payload/fluent.rs
src/payload/foundationdb.rs
src/payload/json.rs
src/payload/splunk_hec.rs
src/payload/syslog.rs

Back when this project first started there were not many different kinds of
payload and only two generators. There was an awkward config -> payload switch
table that happened in each generator and, while I did love it, eh. There are
now more generators and more payloads with more on the way and what was once an
annoyance will quickly become a real code duplication problem.
This commit follows the generator/blackhole configuration model and has payload
provide its own configuration. This allows all the generators to drop their
Variant configuration and means introducing a new payload is not a big slog. If
we need generators to serialize differently from one another that is now more
difficult, but is surely something we can address by fiddling with the
Serializer trait.
Signed-off-by: Brian …

Unify Payload configuration

---

.github/workflows/ci.yml
.github/workflows/clippy.yml
Cargo.lock
Cargo.toml
Dockerfile
README.md
clippy.toml
deny.toml
integration/sheepdog/src/lib.rs
src/block.rs
src/payload.rs
src/payload/opentelemetry_log.rs
src/payload/opentelemetry_metric.rs
src/payload/opentelemetry_trace.rs

Add baseline support for generating OTEL payloads. This can be used to generate binary OTLP/HTTP messages. OTLP/gRPC support will be built on top of this.
This is the first piece of OpenTelemetry support.
SMP-7
This takes on all of `tonic` as a dependency. That's not great - it's a heavy dependency and this PR only needs the codegen parts. I'm not too concerned about it because we're going to need tonic for `OTLP/gRPC` support. Related upstream issue: https://github.com/open-telemetry/opentelemetry-rust/issues/873.

Support OTEL payloads

---

integration/sheepdog/src/lib.rs

Use the default OTLP/HTTP URIs and the correct Content-Type header.
Improve the correctness of our integration tests.
SMP-7
Relevant docs section: https://opentelemetry.io/docs/reference/specification/protocol/otlp/#otlphttp-request

Improve OpenTelemetry integration tests

---

Cargo.lock
Cargo.toml
clippy.toml
src/block.rs
src/generator.rs
src/generator/grpc.rs

Add a generic gRPC generator
This enables OTLP/gRPC load generation
SMP-7
Example config:
```yaml
generator:
grpc:
seed: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53,
59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131]
target_uri: "http://[::1]:50051/opentelemetry.proto.collector.logs.v1.LogsService/Export"
bytes_per_second: "100 Mb"
block_sizes: ["1Mb", "0.5Mb", "0.25Mb", "0.125Mb", "128Kb"]
maximum_prebuild_cache_size_bytes: "8 Mb"
variant: "opentelemetry_logs"
```

Add generic gRPC generator

---

src/blackhole/tcp.rs

Track bytes received by the TCP blackhole.
This provides more visibility into incoming TCP streams.
N/A
N/A

Count bytes received by TCP blackhole

---

.github/workflows/container.yml
.github/workflows/release.yml
CHANGELOG.md

Add a release process to the project.
Releases will be triggered by creating a git tag. The `release.yml` workflow will then automatically create a github release with a changelog snippet and then build and upload `lading` binaries. The `container.yml` workflow will build and tag a set of images according to semver.
For now, the changelog should be written manually before release. We may decide to automate that in the future, maybe with additional automation like [release-please](https://github.com/googleapis/release-please).
This allows us to offer predictability and documentation around breaking changes.
Closes #266 
Best reviewed commit-by-commit

Add GitHub release workflow w/ binaries & containers. Add changelog.

---

.github/workflows/container.yml

This change tags PR containers with a `pr-xyz` tag. This makes it a bit easier to test changes from PRs.
Got tired of searching Actions logs for container SHAs.
N/A
Built on https://github.com/DataDog/lading/pull/320. The only new commit here is the last one in the series.

Tag PR containers

---

integration/sheepdog/src/lib.rs
src/bin/lading.rs
src/blackhole.rs
src/blackhole/http.rs
src/blackhole/splunk_hec.rs
src/blackhole/sqs.rs
src/blackhole/tcp.rs
src/blackhole/udp.rs
src/common.rs
src/config.rs
src/generator.rs
src/generator/file_gen.rs
src/generator/grpc.rs
src/generator/http.rs
src/generator/kafka.rs
src/generator/splunk_hec.rs
src/generator/tcp.rs
src/inspector.rs
src/observer.rs
src/payload.rs
src/payload/splunk_hec.rs
src/target.rs

Switch generator & blackhole config sections to (always) be lists.
**This is a breaking change.**
This change allows us to remove the `serde(untagged)` attribute on the relevant config sections. This enables serde to offer a significantly improved debug experience.
Before:
```
Error("blackhole: data did not match any variant of untagged enum Config", line: 14, column: 3)
```
After:
```
Error("blackhole[0]: unknown variant `tcpa`, expected one of `tcp`, `http`, `splunk_hec`, `udp`,
`sqs`", line: 14, column: 5)
```
Closes https://github.com/DataDog/lading/issues/306
See: https://docs.rs/serde_yaml/0.9.13/serde_yaml/with/singleton_map_recursive/index.html

Switch generator & blackhole config to lists

---

.github/workflows/ci.yml

Add caching to our CI jobs. This will cache dependency download & build artifacts.
This should save about a minute of wall time & eight to ten minutes of runner time.
Our CI times are inching upwards. This is the easy first step before doing any compile time analysis.
N/A
- Here's a before & after to verify caching is working and get a rough idea of the impact:
- Before: https://github.com/DataDog/lading/actions/runs/3092062204/jobs/5002899386
- After: https://github.com/DataDog/lading/actions/runs/3092062204/jobs/5003046258

Use rust-cache Action to speed up CI

---

.github/workflows/container.yml
.github/workflows/release.yml

- I forgot to install the protobuf compiler
- The docker image is being tagged with the git tag verbatim, in addition to semver tags. This is unnecessary and confusing.
- <s>Stop tagging images with major version 0</s> Reverted. I can't delete the image that was released as '0', and I'm not too offended by having a '0' major tag. I can unwind this, but I'm not sure it's worth finding a github org admin to help fix.
Fixing up the release workflow
#320 #326 
<s>Unless anyone objects, I plan to delete the 0.10.0 tag, image, and release, retag, and allow the workflow to run again. I'm not against cutting a 0.10.1, but I'm not too concerned about re-tagging a dev version without code changes.</s> I'll cut a 0.10.1 release since I can't delete the 0.10.0 image.

Three fixes to the release workflow

---

src/generator.rs
src/generator/grpc.rs
src/observer.rs
src/target.rs

Fix issues that came up in https://github.com/DataDog/single-machine-performance/pull/154. The primary issue here is the lack of connection retries: the generator was attempting to connect before Vector's gRPC server was available.
Run an OTel experiment
https://github.com/DataDog/single-machine-performance/pull/154
N/A

Fixes for gRPC generator

---

src/bin/lading.rs

Fixes the last warning from updating to rust 1.64
Didn't want to delay #333 with another CI iteration
Fixed the 1.64 clippy dings in https://github.com/DataDog/lading/pull/333
https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html

Fix one last rust 1.64 warning

---

README.md
examples/lading.yaml

Fix lading.yaml examples. `generator` and `blackhole` uses sequence instead of map.

fix lading.yaml examples

---

src/blackhole/http.rs

The doc-comment on `body_variant` says that it defaults to `Nothing`. That wasn't true before, now it is.
Align comments & choose unsurprising defaults.
N/A
I didn't really want to change behavior here, but I think this is the right decision long term.

Align default body variant w/ comment

---

src/bin/lading.rs
src/blackhole.rs
src/blackhole/http.rs

Make the HTTP blackhole's response content type configurable.
This allows http responses to masquerade as anything. The next step will be to add configurable payloads, but we'll cross that bridge when we come to it.
https://github.com/DataDog/lading/issues/101
This required some unpleasantness to pass through to the service handler. I'd typically solve lifetimes for a series of moves with nested clones, but that's insufficient in this case. I worked around it by leaking a box and holding the `Copy` reference in the `FnMut` closure that was causing problems. I would gladly accept suggestions or improvements on this!

Make http blackhole content type configurable

---

src/generator/udp.rs

We've observed an issue where the UDP generator will run forever, ignoring the shutdown signal. This PR biases the UDP generation task towards polling the shutdown signal to avoid this.
Stop `lading` processes from spinning on UDP forever.
N/A
We may consider refactoring shutdown to abort async tasks rather than signal and expect cooperation.

Bias UDP send loop towards the shutdown signal

---

Cargo.lock
Cargo.toml

Release 0.10.3 with UDP generator fix.
Get a release out with working UDP generation.
#372 
N/A

Prepare release 0.10.3

---

CHANGELOG.md
src/blackhole/http.rs

Adds support for arbitrary response headers to the HTTP blackhole.
Filling in a functionality gap that we're likely to need before too long. Convenient airplane work.
#378 
N/A

HTTP blackhole: Support arbitrary response headers

---

CHANGELOG.md
src/generator/grpc.rs

Offer configurable concurrency limit in gRPC generator.
Fill in a notably missing config knob.
N/A
N/A

Configurable gRPC concurrency limit

---

.github/workflows/release.yml
CHANGELOG.md
Cargo.lock
Cargo.toml

Add an S3 release flow for `lading`.
I'll make a release candidate release from this branch before merging.
This is somewhat preferable for some internal use cases.
SMP-230
N/A

Add S3 release flow & prepare 0.10.4 release

---

CHANGELOG.md
src/observer.rs

This is the bare minimum observer for a hierarchy of processes. This will be inaccurate if processes start and stop frequently. It will also panic. I'll resolve the latter issue before marking this PR ready.
We would like to be able to measure static trees of processes. The official Agent containers run an `s6-init` process and one or more `agent` processes. Assumption: these are mostly long-lived.
SMP-237
N/A

Pretty bad hierarchical process observer

---

.github/workflows/release.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
src/generator.rs

Release 0.11.1 with:
- Add an x86-64 musl build
- Update `opentelemetry-proto` to remove the `protoc` dependency
- Make kafka support optional
We would like a musl build for compatibility with non-glibc environments.
SMP-242
[RC release](https://github.com/DataDog/lading/releases/tag/v0.11.1-rc3) ([log](https://github.com/DataDog/lading/actions/runs/3526983488))

Release musl builds + prepare 0.11.1 release

---

.github/workflows/release.yml
CHANGELOG.md

Build release binaries with Ubuntu 20.04. We don't want any surprises with Github Actions rolling out the next LTS sometime soon.
Stability
N/A
N/A

Use Ubuntu 20.04 for glibc based builds

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/bin/lading.rs
src/target.rs

Allow lading to pass its environment variables into the target process.
Some targets expect to use environment variables that are set in the container. This was less of an issue when we were running in bespoke containers.
SMP-242
N/A

Optionally pass lading's environment to targets

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/generator/grpc.rs

Correctly handle gRPC endpoints that return a non-empty response.
The gRPC generator would previously emit an error and drop the response if a non-empty response were returned.
SMP-298
Tonic expects the response decoder to consume the buffer it is provided. It will throw a fairly inscrutible error if this isn't upheld. This isn't normally a problem because most decoders are codegenned.

Fix gRPC generator for endpoints that return data

---

src/generator/file_gen.rs
src/generator/grpc.rs
src/generator/http.rs
src/generator/kafka.rs
src/generator/splunk_hec.rs
src/generator/tcp.rs
src/generator/udp.rs

This PR instruments the bytes per seconds of each generator, save `file_tree`.
We would like to write out the maximum throughput that can be expected for a given
generator, where appropriate, into capture files to aid later analysis. Only
`file_tree` generator is not included here as its throughput concept is
completely alien to the network oriented generators.

Instrument `bytes_per_seconds`

---

src/blackhole/udp.rs

While working on #428 I realized that the UDP blackhole does not write out `bytes_received`. All the other blackholes do write out this metric and it's an oversight that UDP does not.

Write `bytes_received` from UDP blackhole

---

CHANGELOG.md
proptest-regressions/payload/opentelemetry_metric.txt
src/payload.rs
src/payload/opentelemetry_log.rs
src/payload/opentelemetry_metric.rs
src/payload/opentelemetry_trace.rs

This fixes a rounding error in the varint length calculation.
Fix this error: https://github.com/DataDog/lading/actions/runs/3878993580/jobs/6615728387
N/A
N/A

Fix varint length calculation in OTel payloads

---

CHANGELOG.md
src/block.rs
src/payload.rs
src/payload/datadog_logs.rs
src/payload/dogstatsd.rs
src/payload/dogstatsd/common.rs
src/payload/dogstatsd/event.rs
src/payload/dogstatsd/metric.rs
src/payload/dogstatsd/service_check.rs

This commit introduces DogStatsD payload generation into lading. We support all the variants described [here](https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/?tab=metrics). 

Introduce DogStatsD payload generation

---

CHANGELOG.md
src/generator/udp.rs
src/generator/uds.rs

This commit adjusts the UDS generator spin implementation to be more like the UDP implementation in that we no longer crash a subtask if the UDS socket is not available for opening yet. In instances where Datadog Agent is concerned the socket can be available relatively late, harming reliable inspection.

Attempt to recreate UDS stream if not available, rather than crash

---

CHANGELOG.md
src/blackhole.rs
src/blackhole/unix_datagram.rs
src/blackhole/unix_stream.rs
src/generator.rs
src/generator/udp.rs
src/generator/unix_datagram.rs
src/generator/unix_stream.rs
src/payload/dogstatsd/common.rs
src/payload/dogstatsd/event.rs
src/payload/dogstatsd/metric.rs
src/payload/dogstatsd/service_check.rs

This commit improves over the UDS generator, splitting it firmly between stream and datagram implementations. I have confirmed that this works now against Datadog Agent, requiring some fixes to the DogStatsD payload generation.

Make Unix Datagram, Stream distinct, fix DogStatsD bugs

---

Cargo.lock
deny.toml

Full dependency tree update & some cargo deny maintenance. Set cargo deny to reject unknown git sources. 
Dependabot PRs were failing due to an old transitive dependency
Closes #441, #440
N/A

Dependency updates

---

src/generator/file_gen.rs

Peer to #447 this commit adjusts the file generator to use the `select!` approach, now allowing for clean shutdown of the file generator sub-tasks with consistent flushing. This commit also properly allows errors to bubble up from those sub-tasks, where previously they would not.
REF SMP-329

Update file generator to use `select!` approach

---

src/generator/grpc.rs
src/generator/splunk_hec.rs
src/generator/tcp.rs
src/generator/udp.rs
src/generator/unix_datagram.rs
src/generator/unix_stream.rs

It's long nagged at me that we're too aggressive about popping blocks of a block cache. Consider that previously we would pull a block off the cache, realize we had no connection, drop the block, establish a connection and _then_ pop a block and use that. It's not wasteful per se since we're cycling through no matter what but it doesn't sit right, considering that the goal is for our cycle to be consistent each time.

Prefer to peek blocks

---

src/bin/lading.rs
src/generator/file_gen.rs
src/generator/file_tree.rs
src/generator/grpc.rs
src/generator/http.rs
src/generator/process_tree.rs
src/generator/splunk_hec.rs
src/generator/tcp.rs
src/generator/udp.rs
src/generator/unix_datagram.rs
src/generator/unix_stream.rs
src/observer.rs
src/target.rs

This commit adds the ability for lading generators to back off from pushing load if the target program gets close to a user-supplied memory limit. 
This implementation is stop/start. I think in the future it'd be a boon if we made back-off scale back attempted throughput, although we'll also have to administer a scale-up. We've discussed that a PID would work just great for this kind of thing but I think achieving that is outside the scope of this PR for now.
REF SMP-329

Allow for back-off based on target memory limits

---

src/payload/dogstatsd/common.rs
src/payload/dogstatsd/event.rs
src/payload/dogstatsd/service_check.rs

This commit chops down the possible cardinality of the metrics, events and service checks built by the DogStatsD payload generator. It allows for us to push load without experimenting solely on a target's memory recollection approach. See also #445.
REF SMP-329

Constrain DogStatsD key/value and name cardinality

---

src/block.rs
src/generator/file_gen.rs
src/generator/file_tree.rs
src/generator/grpc.rs
src/generator/http.rs
src/generator/process_tree.rs
src/generator/splunk_hec.rs
src/generator/splunk_hec/acknowledgements.rs
src/generator/tcp.rs
src/generator/udp.rs
src/generator/unix_datagram.rs
src/generator/unix_stream.rs
src/lib.rs
src/throttle.rs

This commit takes our use of governor crate as well as the recent RSS limiter and hides it inside a `Throttle` type that all generators now reference. I have needed to spread `thiserror::Error` implementations around through this work, which also unifies that aspect of our error handling.
There should be no happy-path functional change here. The ambition is to allow us to hunt for setpoints in generation but making changes in ten distinct generators to support that goal is, well, a dead-end.
REF SMP-372

Unify limiting under a `Throttle` type

---

CHANGELOG.md
src/observer.rs

Use saturating addition in the observer's stats gathering routine. This fixes a panic when the target process doesn't have a memory limit (`rsslim == u64::MAX`)
Fix the panic reported in https://github.com/DataDog/lading/issues/463
https://github.com/DataDog/lading/issues/463
N/A

Use saturating addition in observer

---

src/generator.rs
src/generator/unix_datagram.rs

This commit allows `unix_datagram` users to configure parallel connections, akin to our gRPC and HTTP generators. This came about while working on #466 at the suggestion of @GeorgeHahn and it struck me as a good, very achievable improvement.

Allow unix datagram generator to have parallel connections

---

.github/workflows/ci.yml
.github/workflows/release.yml

The 1.4.0 release of the [Rust toolchain action](https://github.com/actions-rust-lang/setup-rust-toolchain) we use broke CI. Pin to a specific version & roll back to the last working version.
Fix CI
Upstream issue: https://github.com/actions-rust-lang/setup-rust-toolchain/issues/9
N/A

Use specific rust action tag

---

CHANGELOG.md
Cargo.lock
Cargo.toml
integration/sheepdog/src/lib.rs
src/generator/file_tree.rs
src/generator/process_tree.rs
src/throttle.rs

This pull request replaces our throttle mechanism based on [governor](https://docs.rs/governor/latest/governor/) with a similar cell rate algorithm but one where the 'capacity' of the leaky bucket shifts in response to actual use. This allows lading to automatically search out stable throughput points in clients. 
We're experimenting on Agent and discovered that in some configurations -- UDS with DogStatsD, notably -- we could force the Agent's ingress throughput to demonstrate high standard deviation. At low throughput -- 256 KiB/sec -- this problem went away, implying there was stable point somewhere between 1 GiB/sec and 256 KiB/sec. We want lading to search this point out automatically.
REF SMP-372

Capacity threshold search

---

Cargo.lock
integration/sheepdog/Cargo.toml
integration/sheepdog/src/lib.rs

In #491 we ran into a dependency update issue revolving around `assert_fs` in sheepdog, as well as that crate using a `tempfile` version dinged by RUSTSEC-2023-0018. We have issued https://github.com/assert-rs/assert_fs/pull/93 to that crate but it also is the case that we can use `tempfile` directly, it seems, here and remove the dependency on `assert_fs`.

Remove `assert_fs` dependency

---

CHANGELOG.md
src/observer.rs

Aggregate the PSS value for all maps in all processes under observation. This will give a more accurate view of overall memory usage for process hierarchies that share memory.
Improve our memory measurements

Add Proportional Set Size (PSS) support to observer

---

CHANGELOG.md
rust-toolchain.toml
src/blackhole/sqs.rs
src/block.rs
src/codec.rs
src/generator/http.rs
src/payload.rs
src/payload/apache_common.rs
src/payload/opentelemetry_log.rs
src/payload/opentelemetry_metric.rs
src/payload/opentelemetry_trace.rs
src/payload/trace_agent.rs

This commit introduces support for the Datadog Agent tracing span, defined [here](https://github.com/DataDog/datadog-agent/blob/main/pkg/trace/pb/span.proto). In practice this will be combined with the HTTP generator to POST payloads toward the Agent.
As of this commit -- as noted in the code -- the shrink algorithm in our payload creation isn't quite right, but I'm sure something will come to me tomorrow.
REF SMP-410

Introduce support for TraceAgent payload

---

CHANGELOG.md
Cargo.toml
src/block.rs

The `Bytes` type is really useful when you need to share the underlying `Vec<u8>` without modification and our `Block` type is basically a fancy holder for `Vec<u8>` with continual clones. The idea for this occurred to me in #506 although I didn't want to include it there.
There might be other locations in our codebase where `Bytes` is more appropriate than `Vec<u8>`.

Convert `Block` to use `Bytes` type not `Vec<u8>`

---

CHANGELOG.md
Cargo.lock
Cargo.toml

- Introduced Proportional Set Size (PSS) memory measurement under the
`pss_bytes` metric.
- Convert `Block` to use `Bytes` type instead of `Vec<u8>`.
- Introduce Datadog trace-agent payload support in JSON and MsgPack serialization.
SMP-448

Prepare release 0.13.1

---

.github/labeler.yml
.github/workflows/labeler.yml

Automatically apply the `needs_changelog` label to PRs that need a changelog entry.
Help keep the changelog filled in.

Automatically label PRs missing a changelog entry

---

.github/workflows/ci.yml
integration/sheepdog/src/lib.rs

The hardcoded timeout was being hit periodically in CI. This extends the timeout to 30 minutes and adds a timeout to the CI workflow.
Eliminate the CI flakiness that this showed up as.

Extend integration test timeout

---

.github/labeler.yml
.github/workflows/labeler.yml

Fix labeler globs. Skip labeler entirely for dependabot PRs.
#512

Fix globs & skip label on dependabot PRs

---

.github/workflows/regression_trusted.yml
CHANGELOG.md
src/bin/lading.rs
src/config.rs
src/generator.rs
src/target.rs

The lading-under-test in regression detector workflows needs a target config. Options are either the measurement lading, a dummy target, or no target.
This PR chooses to add a no-target option with the intention to follow up with an 'unlimited' throttling option.
Regression detector bringup
#514

Add no-target option to lading

---

.github/workflows/regression_trusted.yml

The experiment duration is currently 600 seconds, but the target lading was exiting after the default of 120 seconds. This change makes it run to the end of the experiment.

Set lading experiment duration

---

.github/workflows/regression_trusted.yml

Update 'outer' lading with support for experiments that don't have a generator.
This allows `apache_common_http_to_blackhole` to function.
#514

Run regression detector with the release candidate

---

regression/cases/apache_common_http_to_blackhole/experiment.yaml

Fixup for #530. Delete invalid Regression Detector experiment.

Fixup: delete invalid experiment

---

.github/workflows/regression_trusted.yml
regression/cases/apache_common_http_both_directions_this_doesnt_make_sense/lading-target/lading.yaml
regression/cases/apache_common_http_both_directions_this_doesnt_make_sense/lading/lading.yaml
regression/cases/blackhole_from_apache_common_http/lading-target/lading.yaml

Fix both existing experiments.

Point target lading caps to `/dev/null` & use http blackhole

---

src/generator/file_gen.rs
src/generator/grpc.rs
src/generator/tcp.rs
src/generator/udp.rs
src/generator/unix_datagram.rs
src/generator/unix_stream.rs

This is an extraction from #539. The use of the metrics-rs macros are cheap but not free and we have been using them in hot loops. This commit pre-registers metrics with their labels before use, reducing that cost.
REF SMP-463

Register metrics where possible.

---

src/payload/trace_agent.rs

This commit determines by experimentation that our search for a payload size of the just right variety was too stingy: we could be much more aggressive. This is done. Upfront we compute a tree of 10k members and then each time we find that the tree is too small we tack on an additional 5k.
Extracted from #539
REF SMP-463

Improve trace-agent payload generation speed

---

src/block.rs
src/payload.rs
src/payload/datadog_logs.rs

It turns out that we call `Serializer::to_bytes` an awful lot at startup. Prior to #532 when we made new instantiated types we were doing little more than transmuting from bytes. Now, however, we perform some allocations and this process is much, much slower. A pure `Distribution` based approach for allocated types is too slow for some payloads, Datadog logs being one.
This commit adjusts the payload to use the `Generator` trait and allocate in one shot. This makes our startup time tolerable for this payload. Note also the search for serialized payload sizes includes an experimental constant but does not rely on this constant being especially accurate.
Extracted from #539
REF SMP-463

Adjust Datadog Log payload to use `Generator` trait

---

CHANGELOG.md

This release allows the user to configure details about the DogStatsD payload in addition to carrying non-trivial performance improvements. Please see the CHANGELOG for details.

Release lading 0.14.0

---

.github/labeler.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
src/bin/lading.rs
src/config.rs
src/lib.rs
src/target_metrics.rs
src/target_metrics/expvar.rs

Collect Go expvars from the target at runtime.
This allows for analysis that involves introspection into the target application.
SMP-461

Support for collecting Go Expvar target metrics

---

src/blackhole/http.rs
src/blackhole/sqs.rs
src/blackhole/tcp.rs
src/blackhole/udp.rs
src/blackhole/unix_datagram.rs
src/blackhole/unix_stream.rs

This commit pre-registers metrics in our blackholes, a peer to #544. I have made use of OnceCell in situations where a registered metrics needs to cross task boundaries. Fortunately in our blackholes we do not use labels in our metrics so this was a fairly total conversion.

Pre-register more metrics in the blackholes

---

CHANGELOG.md
src/target_metrics.rs
src/target_metrics/expvar.rs
src/target_metrics/prometheus.rs

Adds support for scraping target metrics in the Prometheus/OpenMetrics format. Only counters and gauges are supported.
Support better visibility into target applications
SMP-492

Support Prometheus target metrics

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Release target metrics support & throttle fix (notably impacts the UDP generator)
---
- Added target metrics support for Go expvars
- Added target metrics support for Prometheus
- Fixed throttle behavior for generators that run very quickly

Prepare release 0.15.0

---

src/payload/common.rs

This commit removes non-letter, non-number characters from the AsciiString pool. This is intended to correct a situation where we would sometimes generate invalid DogStatsD metric names. We might consider intentionally constructing metric names et al from a more explicit grammar but this is an acceptable and relatively easy fix.
REF SMP-514

Slightly adjust AsciiString alphabet

---

src/block.rs
src/config.rs
src/generator.rs
src/generator/file_gen.rs
src/generator/grpc.rs
src/generator/http.rs
src/generator/tcp.rs
src/generator/udp.rs
src/generator/unix_datagram.rs
src/generator/unix_stream.rs
src/payload.rs
src/payload/dogstatsd.rs

This commit allows a user to set the probability of, say, a DogStatsD metric being created in a payload compared to a service-check. The ambition here is to allow for experiments that produce only metrics, or mostly service-checks etc. We preserve the existing behavior by weighting all kinds equally.
I have adjusted how we parse the dogstatsd payload config, making more field optional, preserving backward compatibility overall.
REF SMP-513

Allow users to set weights for the kinds of DogStatsD

---

CHANGELOG.md
src/block.rs
src/payload/dogstatsd.rs
src/payload/dogstatsd/metric.rs

This commit allows the user to specify the relative ratios of the metric variants in dogstatsd payload. This is a follow-up from #569.
REF SMP-515

Introduce metric weighting in dogstatsd payload

---

src/generator/udp.rs
src/throttle.rs
src/throttle/predictive.rs

This commit allows generators to provide a configuration option for their throttle, here only udp is converted. The ultimate ambition is to allow for two additional throttle variants: all-out and stable. We rename the existing throttle to 'predictive' and set this as the default. Note that the throttle is implemented in terms of an enum. I did attempt to make this static dispatch because throttle is called in our hot loops but found the intrusion into the codebase too high, especially with consideration of the throttle being present determined at runtime.
REF SMP-520
REF SMP-521

Introduce configurable throttle

---

src/throttle.rs
src/throttle/predictive.rs

This PR builds on https://github.com/DataDog/lading/pull/573 and introduces a throttle that allows the caller to go as
fast as possible. There is actually no throttle here, per se, only a
configuration option and a branch.
Please review #573 before this one. 
REF [SMP-520](https://datadoghq.atlassian.net/browse/SMP-520)
REF [SMP-521](https://datadoghq.atlassian.net/browse/SMP-521)
[SMP-520]: https://datadoghq.atlassian.net/browse/SMP-520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SMP-521]: https://datadoghq.atlassian.net/browse/SMP-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

All out throttle

---

src/throttle.rs
src/throttle/predictive.rs
src/throttle/stable.rs

This commit builds on https://github.com/DataDog/lading/pull/573 and https://github.com/DataDog/lading/pull/574 to introduce a 'stable' throttle. It's
implementation is similar to the predictive throttle excepting that we do not
adjust an internal 'budget', capacity refills as time ticks forward.
REF [SMP-520](https://datadoghq.atlassian.net/browse/SMP-520)
REF [SMP-521](https://datadoghq.atlassian.net/browse/SMP-521)
[SMP-520]: https://datadoghq.atlassian.net/browse/SMP-520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SMP-521]: https://datadoghq.atlassian.net/browse/SMP-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Stable throttle

---

CHANGELOG.md
Cargo.lock
Cargo.toml

This commit introduces changes to the throttle mechanism and expands on the configuration possibilities open to users in the DogStatsD payload.

Release 0.15.1

---

CHANGELOG.md
src/payload/dogstatsd/metric.rs

This commit fixes a bug in the last release. We allowed for the creation of DogStatsD metrics that have no values associated with them with probability 1/33. We now require at least one value and do not adjust the maximum of 32.
REF SMP-527

Always include at least one value in a DogStastD metric

---

CHANGELOG.md
Cargo.lock
Cargo.toml

This commit fixes a bug where we may create DogStatsD metrics with no values, release 0.15.2.

Release lading 0.15.2

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/block.rs
src/generator/file_gen.rs

Previously we constructed a separate block cache for each write child in `file_gen`. This meant as we got more duplicate file writes we increased the memory by the prebuild cache size. This lead to situations where lading would OOM if the number of write children were high enough.
REF SMP-558

Share pre-computed block between file write children

---

.github/workflows/regression_trusted.yml

Update `smp` and `lading` in the regression detector workflow. Most importantly, this updates from the deprecated (and no longer working) `smp` version `0.7.2`.
Routine maintenance

Regression detector workflow: update `smp` and `lading`

---

CHANGELOG.md
src/generator/unix_datagram.rs

Datagram connect errors were previously hidden at `trace` level. This PR bumps that up to `error` level to surface them.

Log datagram connect errors as errors

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/bin/lading.rs
src/generator.rs
src/generator/unix_datagram.rs
src/generator/unix_stream.rs
src/inspector.rs
src/observer.rs
src/target.rs

Running `lading` in no-target mode would previously cause a hang if any lading `Servers` were waiting on the PID sender broadcast channel. This is the main point of synchronization in lading startup. This is modified to send an `Option::None` in no-target mode.
This PR also adds a synchronization step to the `unix_datagram` generator. Its behavior now matches other generators and will wait for `fn spin` to be called before running. It previously started running as soon as it was created.

Fix hang in no-target mode & wait for startup in `unix_datagram` generator

---

CHANGELOG.md
src/generator/file_gen.rs
src/generator/file_tree.rs
src/generator/grpc.rs
src/generator/http.rs
src/generator/process_tree.rs
src/generator/splunk_hec.rs
src/generator/tcp.rs
src/generator/udp.rs
src/generator/unix_datagram.rs
src/generator/unix_stream.rs
src/throttle.rs
src/throttle/predictive.rs
src/throttle/stable.rs

This PR labels each throttle's metrics with its parent generator's labels. This will separate the metrics for different throttles to give visibility into each generator's throttles when multiple are in use.
Debugging multi-generator setups.

Add labels to throttle metrics

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

This introduces a dev container that allows for lading's Linux flagged features to be worked from an OS X laptop without the use of a VM. This should not intrude on dev setups that already use a VM, but this would be good to verify.

Add a VSCode remote container setup

---

src/observer.rs

This commit slightly tweaks how we tally up our tick and number of thread data. Instead of immediately converting to a u64 we sum every interior i64 and only then take the unsigned absolute value. The code is a little more tidy than it was and at the extreme end of the value range we avoid losing some information.
REF SMP-612

Slightly tweak how observer performs math operations

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/observer.rs

This commit updates the observer with the aim of calculating CPU utilization. We maintain output of user and kernel space CPU seconds but add utilization with the understanding that this is useful to users that need to consider utilization and not ticks.
Note, if there is CPU use in the system that is not in a parent, child relationship but should still be counted this change will not address that.
REF SMP-613
#613

Update observer to collect CPU utilization data

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/throttle.rs

We have found in practice that many of our users set their throttle to 'stable'. While predictive throttle is valuable and we wish to retain it this being the default is often confusing.
This change is technically breaking. Should be merged behind PR #616 to appear in the changelog.

Adjust the default throttle to 'stable'

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/payload/json.rs

Delete a debug println in the json payload generator
This is spamming logs and likely has significant performance impact.

Delete debug println

---

.github/workflows/ci.yml

These are flaky and it's annoying. We don't depend on Mac builds, so this can be removed.
Improve CI reliability.

Stop running integration tests on Macos

---

.github/workflows/ci.yml

This commit adjusts our CI workflow to ensure that any change we make to project protobufs are perfectly forward and backward compatible.
REF SMP-631

Enforce forward/backward compatibility with buf

---

CHANGELOG.md
lading/src/bin/lading.rs

Supports an environment variable `LADING_CONFIG` that can contain the exact same yaml as the current config. The environment variable takes precedence over the on-disk config.
This is useful in a kubernetes deployment file to avoid the need for a config-map to put a file on disk. It keeps all config tightly coupled to the `lading` pod.
none.
This is useful to me, but I have no strong opinions if its a good fit for lading upstream. I defer to your vision for lading whether or not you want to merge this.

Allow lading config to be specified via env var

---

.vscode/settings.json
CHANGELOG.md
Cargo.lock
lading/Cargo.toml
lading/src/observer.rs
lading/src/observer/linux.rs

This commit modifies how we collect procfs data: we now distinguish children from their parent. Previous versions of lading rolled this information up into one time series but were now distinguish them with labels. This allows users interested only in the roll-up to continue sum over names if they wish.
We have dropped tick series. It saves some room in the capture file and tick information was not found to be useful in practice.
REF SMP-631

Collect procfs data per-process

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

This commit introduces per-process CPU utilization and memory data in lading observer and allows the lading config to be set via environment variable.

Release lading 0.17.2

---

lading/src/block.rs
lading/src/payload/dogstatsd.rs
lading/src/payload/dogstatsd/metric.rs

In DogStatsD it is allowable for a metric line to have multiple values. In practice, this is rare. Our previous 1/32 odds of producing only a single-valued line makes lading's output unusual. This is not a bad thing but it is behavior that we want users to be able to configure.
For the purposes of backward compatibility we maintain the same 1/32 odds.
REF SMP-663

Allow users to configure metric multivalue weights

---

CHANGELOG.md
lading/src/payload/dogstatsd/metric.rs

This PR corrects a bug in how multi-value metrics are formed. The SET metric is not allowed to have multiple values, although we would produce such metrics.
Closes #650
REF SMP-664

Do not send multiple value for a DogStatsD SET metric

---

.github/workflows/ci.yml
CHANGELOG.md
Dockerfile
lading/Cargo.toml
lading/src/block.rs
lading/src/captures.rs
lading/src/generator/grpc.rs
lading_capture/Cargo.toml
regression/Dockerfile
rust-toolchain.toml

Update Rust compiler to version 1.71.0.
I noticed that the container toolchain was out of sync with the rest of the repo.

Update to rust 1.71.0

---

.github/workflows/release.yml
CHANGELOG.md
Cargo.lock
lading/Cargo.toml
lading_capture/Cargo.toml

Prepare lading crates for publishing to crates.io.
This will get lading docs on docs.rs and will let us take a versioned dependency on `lading-capture`.

Prepare release to crates.io

---

Cargo.lock
lading_payload/Cargo.toml
lading_payload/benches/default.rs
lading_payload/benches/dogstatsd.rs
lading_payload/src/dogstatsd.rs

In #671 we moved the payload module into a new crate in order to make it easier to add benchmarks for payload generation. This is now done, we have benchmarks for dogstatsd. Of note, we benchmark setup time -- ~30ms -- and throughput, the later shows the real influence of our longish setup time: the more bytes we generate the better the throughput.
It does strike me that the `Serialize` trait will not be suitable for streaming, REF #666. Some payloads like dogstatsd can stream per-message but others require serialization into a container. How to deal with the container notion in a stream, I'm not sure. Something to think about.
REF SMP-673

Introduce benchmarks for `lading_payload`

---

lading/src/block.rs
lading_payload/benches/ascii.rs
lading_payload/benches/default.rs
lading_payload/proptest-regressions/common/strings.txt
lading_payload/src/ascii.rs
lading_payload/src/common.rs
lading_payload/src/common/strings.rs
lading_throttle/src/stable.rs

This commit is born of the work on #666. We realize in that PR that we spend most of our runtime producing small heap allocated strings. This PR introduces `Pool` which allows the user to request a small `&str` of a given size. It is hooked up to only a single payload -- Ascii -- but will be introduced elsewhere in follow-up work.
REF SMP-664

Introduce a pool mechanism for producing small strings

---

lading_payload/src/bin/lading_rev.rs
lading_payload/src/common.rs
lading_payload/src/common/strings.rs
lading_payload/src/dogstatsd.rs
lading_payload/src/dogstatsd/common/tags.rs
lading_payload/src/dogstatsd/event.rs
lading_payload/src/dogstatsd/metric.rs
lading_payload/src/dogstatsd/metric/template.rs
lading_payload/src/dogstatsd/service_check.rs

This commit begins the process of converting the dogstatsd payload generation to use the new string pool, introduced in #675. I have only partially converted the event sub-payload -- note that tagsets have not been switched yet -- and this shows a 6% improvement to `dogstatsd_setup` and a 5% - 74% improvement to `dogstatsd_all`. It shows there's some promise to the technique that improves as we scale up the total-bytes emitted.
EDIT: By the final commit we're capping _all out at 1Gb/s, up from ~300Mb/s. 
Of note I will need to eventually convert the `Generator` trait to emit a type with a lifetime. Since I can't do that incrementally the `generate` function in select areas temporarily does not come from the trait. This will have to be resolved by converting all the payloads to non-copying …

Convert DogStatsD payload to use string pool

---

lading_payload/src/apache_common.rs
lading_payload/src/datadog_logs.rs
lading_payload/src/dogstatsd/common/tags.rs
lading_payload/src/dogstatsd/event.rs
lading_payload/src/dogstatsd/metric.rs
lading_payload/src/dogstatsd/service_check.rs
lading_payload/src/fluent.rs
lading_payload/src/json.rs
lading_payload/src/lib.rs
lading_payload/src/opentelemetry_log.rs
lading_payload/src/opentelemetry_metric.rs
lading_payload/src/opentelemetry_trace.rs
lading_payload/src/trace_agent.rs

Follow-up to #680. I realized that the Generator trait could be used with an associated type to cover owned and reference returns just after #680 merged up. This commit slightly expands the definition of `Generator` and ensures its general use.
REF SMP-664

Use associated types in Generator trait

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml
lading/src/block.rs
lading/src/common.rs
lading/src/config.rs
lading/src/generator.rs
lading/src/generator/file_gen.rs
lading/src/generator/grpc.rs
lading/src/generator/http.rs
lading/src/generator/splunk_hec.rs
lading/src/generator/tcp.rs
lading/src/generator/udp.rs
lading/src/generator/unix_datagram.rs
lading/src/generator/unix_stream.rs

This commit makes two major changes to the block cache. The most important is that the block cache's major CPU consumption -- the construction of `Block` instances -- is now done in a separate OS thread from the tokio runtime. This allows us to introduce the second more important change: infinite streams of `Blocks`. It is now possible for users to construct an unending stream of `Block` instances that do not loop. We maintain a cache of constructed `Block`s up to the maximum total bytes allow to minimize any potential latency impact.
Configuration is changed but not in a backward incompatible way.
REF SMP-664

Block cache with an infinite stream option

---

Cargo.lock
Cargo.toml
lading/Cargo.toml
lading/src/bin/lading.rs
lading/src/blackhole/splunk_hec.rs
lading/src/captures.rs
lading/src/config.rs
lading/src/generator/process_tree.rs
lading/src/generator/splunk_hec/acknowledgements.rs
lading/src/inspector.rs
lading/src/target.rs
lading/src/target_metrics/prometheus.rs
lading_capture/Cargo.toml
lading_capture/src/json.rs
lading_payload/Cargo.toml
lading_payload/src/fluent.rs
lading_payload/src/trace_agent.rs

This commit adjusts more of our codebase to use the FxHash instead of the randomly seeded Hash{Map|Set}. We want to avoid sources of non-determinism. We believe many of our dependencies will use randomly seeded HashMaps and this commit does nothing to address that.
REF SMP-687

Prefer the use of FxHash over Hash

---

lading_payload/src/dogstatsd.rs

Changes the units to a larger numerical type that can support >65k contexts. Shouldn't require any other changes past the config layer as the generator converts into a usize which should always fit a u32.
I have observed hosts running in the wild with 800k contexts, this should be supported by our dogstatsd generator.

Switches context range from u16 with a max limit of 65k to a u32

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml
lading/src/block.rs
lading_payload/src/dogstatsd.rs
lading_payload/src/dogstatsd/common.rs
lading_payload/src/dogstatsd/metric.rs

This commit introduces a configuration option to allow the user to define the range of values that appear in DogStatsD metrics. This range applies to all metric kinds. The distribution is changed from Standard -- "numerically uniform" -- to actually Uniform. We do not allow users to configure the distribution.
REF SMP-694

Allow the user to configure the range of DogStatsD metrics

---

lading/src/target_metrics/prometheus.rs

Silences prometheus target metrics warnings
```
2023-10-10T17:38:53.943589Z  WARN lading::target_metrics::prometheus: invalid float literal: aggregator_tags_store.tagset_refs_count = #0",ge="8"}
```
This format isn't described in the [prometheus format doc](https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md). Leave this unimplemented until it's necessary.

Silence prometheus float format warnings

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.lock
lading/Cargo.toml
lading/src/block.rs
lading_payload/proptest-regressions/common/strings.txt
lading_payload/proptest-regressions/dogstatsd.txt
lading_payload/src/common/strings.rs
lading_payload/src/dogstatsd.rs
lading_payload/src/dogstatsd/common.rs
lading_payload/src/dogstatsd/common/tags.rs
lading_payload/src/dogstatsd/event.rs
lading_payload/src/dogstatsd/metric.rs

We have the need to specify constant values for some of our range constructions in dogstatsd payloads. This commit allows that behavior, although users must now be explicit about the constant or inclusive setup they intend. This will be very helpful in experimenting with the Agent, we believe.
REF https://github.com/DataDog/datadog-agent/pull/19993 
REF SMPTNG-24

Adjust dogstatsd configuration to allow for constant values

---

lading/src/blackhole/http.rs

Add support to the blackhole to return a raw byte array/vector response. This is to support custom binary types which is used by the datadog process agent.
**1. Baseline**
Running the agent with the `nothing` response from lading shows the process agent logs errors due to the invalid/empty response
```yaml
- http:
binding_addr: "127.0.0.1:9092"
body_variant: "nothing"
```
```
2023-10-16 20:11:43 UTC | PROCESS | ERROR | (pkg/process/runner/runner.go:489 in readResponseStatuses) | [process] Could not decode response body: invalid message length: 0
```
**1. Process Response RT Mode Disabled**
```yaml
- http:
binding_addr: "127.0.0.1:9092"
body_variant: "raw_bytes"
raw_bytes: [0x1, 0x0, 0x17, 0x0, 0xa, 0x2, 0x20, 0x17, 0x1a, 0x2, 0x10, 0xa]
```
The process agent logs show no errors from the …

add support for raw byte for http response body

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

Prep a 0.19.0-rc4 release candidate
Get https://github.com/DataDog/lading/pull/704 into a released build
Ref PROCS-3308

Prepare 0.19.0-rc4 release

---

CODEOWNERS

This commit makes the Single Machine Performance team required reviewers of every PR. This formalizes an informal process we've kept in place for the last year and change.

Make Single Machine Performance official code owners

---

CHANGELOG.md
lading/src/blackhole/http.rs

Fix the metrics emitted by lading's http blackhole.
Fix our view of agent egress.
SMPTNG-1

HTTP blackhole: fix `bytes_received` and `requests_received` metrics

---

CHANGELOG.md
lading/src/target_metrics/prometheus.rs

Report scraped Prometheus counters correctly. This fixes a double aggregation that we observed in metrics scraped from targets.
Fixes
SMPTNG-1

Report scraped counters without aggregation

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml
lading/src/generator/file_gen.rs
lading/src/generator/file_gen/traditional.rs

This commit introduces a change where the existing file-generator is renamed "traditional" and as a matter of configuration it's now possible to slot more kinds of file generators into the system. This is not done in this PR.
REF SMPTNG-6
REF SMPTNG-44
REF SMPTNG-45

Allow for more file generators to be configured

---

CHANGELOG.md
lading/src/generator/file_gen.rs
lading/src/generator/file_gen/logrotate.rs

This commit introduces a new log generator that is able to mimic logrotate's operation. This also allows us to mimic how kubernetes logs work by setting `total_rotations` to be zero.
REF SMPTNG-44

Introduce 'logrotate' log generator

---

.github/workflows/ci.yml
lading_throttle/src/stable.rs

This commit adjusts the proofs that we have in our stable throttle to avoid a loop and instead rely on a series of smaller proofs. This terminates in a reasonable amount of time. Note I've removed the proptests and this commit will need to be followed by another than runs kani in CI.
I may still be missing a few small properties.
REF SMPTNG-79

Adjust proofs for stable valve in throttle

---

Cargo.toml
lading_throttle/src/stable.rs

Follow-up from PR #721, plus a change to pin the resolver to 2 to avoid a compiler warning.

Address feedback on #721

---

.github/workflows/ci.yml
lading/src/generator/file_gen/logrotate.rs
lading/src/generator/file_gen/traditional.rs
lading/src/generator/grpc.rs
lading/src/generator/http.rs
lading/src/generator/splunk_hec.rs
lading/src/generator/tcp.rs
lading/src/generator/udp.rs
lading/src/generator/unix_datagram.rs
lading/src/generator/unix_stream.rs
lading_payload/src/block.rs

This commit adds proofs for the `chunk_bytes` function, converting its interface to be in terms of `u32` -- as matches our configuration -- and also to use a round-robin method internally to avoid randomness. The callers -- two sites -- are responsible for passing  `chunks` in as a mutable reference, allowing us to bound the maximum iterations of this function. The function is now allocation-free, although the change as a whole is neutral in this regard. 
REF #724
REF SMPTNG-79

Introduce proofs for block mechanism

---

lading_payload/src/block.rs
lading_payload/src/statik.rs

Discovered by the fuzzing work introduced in #727 we do not want to panic in the constructor for the static generator but instead kick out errors.
REF SMPTNG-79

Adjust static generator to not panic

---

lading_payload/src/dogstatsd.rs
lading_payload/src/dogstatsd/common/tags.rs
lading_payload/src/dogstatsd/event.rs
lading_payload/src/dogstatsd/metric.rs
lading_payload/src/dogstatsd/service_check.rs

This commit modifies the tag generator to generate tagsets at-time. The way we maintain context constraints is novel in the project: we maintain an internal RNG that we deterministically reseed when we loop around the number of contexts.
Follow-up from #727.
REF SMPTNG-79

Convert the generation of tagsets to at-time

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

This commit creates an -rc4 release that incorporates the memory fixes and stability done as a part of SMPTNG-79.

Cut release 0.20.0-rc4

---

lading_payload/src/dogstatsd.rs

Re-adds the `DogStatsD#generate` public function that was removed in #727 .
Simple usage of the dogstatsd generator outside of this project.
Stacked with #741

Re-adds generate

---

Cargo.lock
lading/Cargo.toml
lading/src/captures.rs

This commit makes use of generational storage in the CaptureManager, expiring keys that have not been written to for ten seconds. After this period the keys will no longer be written out. This is especially important for observer metrics in the presence of short-lived processes.
REF SMPTNG-85

Use generational storage in the CaptureManager

---

examples/dogstatsd-generation.yaml

Previous example dogstatsd config had a bug where weights of metric_kinds added up to greater than a `u8`.
Corrects some of the specific values as well.

Corrects example dogstatsd configuration

---

lading/src/bin/lading.rs
lading/src/signals.rs

This commit removes the soft shutdown that we previously used in lading. We have known for some time that lading's shut down mechanism is faulty: singular tasks would hold the shutdown up for unknown reasons. We then used the runtime shutdown in addition to our soft mechanism.
This commit removes the soft mechanism. We signal that all tasks _should_ shut down but no longer wait on them to do so, immediately moving to the runtime's shutdown mechanism.
REF SMPTNG-94

Signal shutdown, use runtime shutdown to stop

---

amd64.Dockerfile
arm64.Dockerfile
lading/src/blackhole/http.rs
lading/src/blackhole/splunk_hec.rs
lading/src/blackhole/sqs.rs
lading/src/blackhole/tcp.rs
lading/src/blackhole/udp.rs
lading/src/blackhole/unix_datagram.rs
lading/src/blackhole/unix_stream.rs
lading/src/captures.rs
lading/src/generator/file_gen/logrotate.rs
lading/src/generator/file_gen/traditional.rs
lading/src/generator/file_tree.rs
lading/src/generator/grpc.rs
lading/src/generator/http.rs
lading/src/generator/process_tree.rs
lading/src/generator/splunk_hec.rs
lading/src/generator/tcp.rs
lading/src/generator/udp.rs
lading/src/generator/unix_datagram.rs
lading/src/generator/unix_stream.rs
lading/src/inspector.rs
lading/src/observer.rs
lading/src/target.rs
lading/src/target_metrics/expvar.rs
lading/src/target_metrics/prometheus.rs
lading_payload/src/block.rs
lading_payload/src/dogstatsd/event.rs
lading_payload/src/dogstatsd/service_check.rs
rust-toolchain.toml

This commit updates our rust toolchain to 1.74 and switches its profile from 'default' to 'complete', meaning rust-analyzer et al are installed now by default for every lading developer.
REF SMPTNG-94

Update lading to Rust 1.74.0

---

integration/sheepdog/src/lib.rs

When run locally this test passes but it fails to operate in CI. Other tests cover similar needs but without the use of TCP. Set this test to ignore.
REF SMPTNG-94

Ignore `tcp_fluent` test

---

Cargo.lock
lading/Cargo.toml
lading/src/captures.rs

Reverts DataDog/lading#748
We have discovered that in lading 0.20.0 this causes a runtime lock. Per our debugging the whole of lading becomes contended on a RWLock and cannot make forward progress. We have not determined the root cause. Because we introduced generational storage to address an edge condition we revert the change for now. 
REF SMPTNG-94

Revert "Use generational storage in the CaptureManager"

---

lading/src/bin/lading.rs

Adds logic in the main `select` loop of `lading` to wait for the result of the generators that were spawned.
While there is good error handling inside the generators that give feedback when an invalid condition is hit, that result was not being read anywhere.

Waits on generator's execution in order to print out any errors

---

Cargo.toml

Make lading abort on panic rather than unwinding. This is an optional change.
The motivation for this change is to exit lading when any panic occurs. We recently observed a case where an async task panicked and tokio gobbled it up and allowed the process to continue blindly. That particular case will be addressed separately, but that's not generally a failure mode we want.
Ref SMPTNG-103

Abort on panic

---

lading/src/bin/lading.rs
lading/src/captures.rs
lading/src/signals.rs

Move the capture manager to its own thread. This makes explicit what tokio was already doing and avoids tokio's panic handler.
The IO routine is adjusted to not panic if serialization or writes fail. This changes the `captures` file contract: each line is now written on a best-effort basis and failure to write one line will not stop ongoing recording. This means we may have invalid lines within a captures file where we previously would have only had them at the end. I believe our capture readers all handle this gracefully today and will ignore the invalid lines.
https://datadoghq.atlassian.net/browse/SMPTNG-105

Move capture manager to background blocking thread

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml
lading/src/generator.rs
lading/src/generator/procfs.rs
lading_payload/src/procfs.rs
lading_payload/src/procfs/proc.rs

This commit completes the work begun in #740 and exposes the purely faked procfs to end users. Nothing very clever is done in this PR. The only novelty is we avoid the use of a block cache and write stringy versions of the generated structs directly to disk. The 'server' constructed here idles entirely.
REF SMPTNG-88

Hook procfs up into the generator, allow for end-user use

---

lading_payload/src/dogstatsd.rs
lading_payload/src/dogstatsd/common.rs
lading_payload/src/dogstatsd/event.rs
lading_payload/src/dogstatsd/metric.rs
lading_payload/src/dogstatsd/service_check.rs
lading_payload/src/lib.rs

This exposes types and fields from dogstatsd message related structs publicly and adds doc-comments as needed.
Motivating example: https://github.com/scottopell/dogstatsd-utils/pull/6
But more generally these could be helpful and don't hurt to expose.

Expose dogstatsd structures publicly

---

Cargo.lock
lading/Cargo.toml
lading/src/bin/lading.rs
lading/src/captures.rs
lading/src/target.rs
lading/src/target_metrics.rs
lading/src/target_metrics/expvar.rs
lading/src/target_metrics/prometheus.rs

This PR implements:
1. An 'experimental' phase that will be entered after the `warmup_duration` expires
2. Modifies the target scrapers and capture manager to not begin execution until the experimental phase has been entered.
i. As part of this, a test for `inner_main` was added which asserts that the expected # of `lading.running` entries given 
a 1 second capture record interval.
4. Refactors the main `select!` in `lading/src/bin/lading.rs` to loop over the `select` to address a potential early-termination bug when the set of `generator`s are empty.
a. This bug was encountered in https://github.com/DataDog/datadog-agent/pull/21452
6. Adds 2 gauge metrics:
a. `lading.running` -- submits a value of `1` as long as the main `select!` of lading is executing
b. `target.running` -- submits a …

AMLII-1328: Adds an 'experimental' phase and removes warmup data from capture

---

lading/src/bin/lading.rs
lading/src/captures.rs

Partially reverts #774 . The 'experimental' phase is still present, however the capture manager no longer waits for the experimental phase to be active before installing the metrics recorder.
This gives us warmup data in the capture files, which some later components rely on currently.
Some components rely on warmup data being present in the capture file.
#774

Switches back to including warmup data in the capture manager

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

Before cutting a `lading` release, its changelog must be updated. This commit updates the changelog in preparation for a 0.20.4 release.
Release changes that should fix broken `idle` experiment in `datadog-agent`.
n/a
n/a

changelog: prep for 0.20.4 release

---

CHANGELOG.md
lading/src/observer/linux.rs

Fix a panic that we've observed in a small number of cases. This switches it from a stability issue into a data-correctness issue. It's expected that the correctness issue will require switching these totals over to cgroup values instead of doing the tally in lading.
https://datadoghq.atlassian.net/browse/SMPTNG-109

Don't panic from tallying resources after process exit

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml
lading/src/generator.rs
lading/src/generator/unix_stream.rs
lading_payload/src/block.rs
lading_payload/src/dogstatsd.rs

See changelog for detailed list, but broadly this branch fixes some bugs in the `unix-stream` generator and adds support for length-prefixed frames in the `dogstatsd` payload generator.
Improve lading to be able to test the new dogstatsd unix-stream support.

AMLII-1319: Unix Stream Dogstatsd Support

---

Cargo.lock
deny.toml

- Updates unsafe-libyaml from 0.2.9 -> 0.2.10 per RUSTSEC-2023-0075"
- Removes un-used git allowed source
Cargo-deny is blocking my release PR #780

Fix cargo-deny advisories

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml
lading/src/bin/lading.rs

Correct tag parsing issue when passed tags use lading's splitting convention. 
We want users to be able to pass tags in Datadog Agent format without needing to make a backward incompatible update to lading. 
REF SMPTNG-124

Correct SMPTNG-124

---

lading/src/generator/unix_datagram.rs
lading/src/generator/unix_stream.rs

Discovered by @tobz we were previously setting the block offset in unix datagram and stream to the bytes written, not incrementing as we should have been. This PR corrects that mistake.

Increment, not reset block offsets

---

Cargo.lock
lading/Cargo.toml
lading/src/bin/captool.rs

Adds a new binary alongside `lading` called `captool` which provides some basic summarization of a given capture file.
The two main functions it serves:
1. Listing out metric names present in the file `--list-names`
2. Printing stats and labels for a given metric name `--metric foo`
The `capture.json` file is full of collected data, but manually sifting through json is no fun.
Example output:
```
2024-01-30T21:37:17.372138Z  INFO captool: Welcome to captool
2024-01-30T21:37:17.434764Z  INFO captool: Metric: smaps_rss
2024-01-30T21:37:17.439565Z  INFO captool: Labels:
pathname: {"/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2", "<empty pathname>", "[stack]", "[vvar]", "/usr/lib/x86_64-linux-gnu/libc.so.6", "/usr/lib/x86_64-linux-gnu/libm.so.6", …
```

Adds tool to quickly summarize capture JSON files

---

lading/src/observer/linux.rs

`exe` is not unique enough, this replaces it with `cmdline` which includes the `exe`.
colliding metrics when different logical processes run off same executable
Would appreciate any thoughts on what to do in the zombie case.

SMPTNG-179: Replaces 'exe' with 'cmdline' for better process detection

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml
lading/src/observer.rs
lading/src/observer/linux.rs
lading/src/observer/memory.rs

Adds support in the linux observer to parse a given PIDs `/proc/pid/smaps` file in order to provide more detail about memory usage.
If RSS increases, it can be difficult to determine exactly _why_ rss went up.
Language-specific profilers and runtime telemetry will be valuable for the parts managed by that language's runtime, but OS-level details can be helpful as well.
REF [SMPTNG-185](https://datadoghq.atlassian.net/browse/SMPTNG-185)
[SMPTNG-185]: https://datadoghq.atlassian.net/browse/SMPTNG-185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Linux 'observer' collects smaps entries and reports them into capture file

---

lading/src/bin/captool.rs

Does a full aggregation across the samples for a given metric name and presents the resulting `average` across that timeseries.
Need to inspect cardinality of data.

Updates captool to print out _all_ valid timeseries for a given metric name

---

lading/src/observer/linux.rs
lading/src/observer/memory.rs

This makes 2 changes:
1. Renames `smaps.rss` to `smaps.rss.by_pathname` for clarity
2. Adds `smaps.rss.sum` which is a sum across all regions
3. Adds a variety of memory-related fields from `proc/status`

Add more memory collection telemetry

---

lading/src/observer/linux.rs
lading/src/observer/memory.rs

Adds `smaps_rollup` view of RSS and PSS.
Interesting to compare against `smaps` and `status`-based telemetry.
Also refactors the `next_token` function that is shared amongst multiple parsing functions now.

Adds smaps_rollup to memory data collection

---

lading/src/observer.rs
lading/src/observer/linux.rs

The `sample` function of the `Observer` is now async and the `smaps` and `smaps_rollup` parsing has been moved into a spawned tokio task, which is `await`ed before the function returns.
I've heard that the `/proc/smaps` file can take up to 250ms to populate in some circumstances, attempt to offload this off the main `sample` thread for now.

Moves smaps and smaps_rollup into an async task since these can be expensive

---

lading/src/captures.rs

Discount the amount of time slept in between capture intervals by the amount of time it took to record the captures.
Mostly preventative, want to avoid time drift in our capture records.

Adjusts the 'capture' sleep to account for any time spent recording the captures

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

This commit releases lading 0.20.6. The most notable change is the inclusion of procfs `smaps` data for monitored processes.

Release lading 0.20.6

---

lading/src/bin/lading.rs

Loosens the assertions to account for scheduling variability in the experiment.
The goal of this test is to provide an "integration" level test where the core loop of `lading` gets run and the assertion is that the `lading.running` gauge is present in the capture json.
This can be accomplished by asserting that there are more than N rather than saying there must be exactly N. Due to scheduling variance, we cannot currently guarantee _exactly_ how many `fetch_indices` there will be.

Adjusts inner_main test to avoid flakeyness

---

lading_payload/src/dogstatsd.rs

Allows taking a constructed `lading_payload::dogstatsd::Config` and serializing it.
Working on a tool that generates lading configs given some ground truth.

Adds SerdeSerialize derive for dogstatsd config

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml
lading/src/observer/memory.rs

The caller of this code handles errors gracefully but in this particular spot we panic if the smaps file cannot be read to string. This is unfortunately a race condition that we hit in practice.

Avoid except in smaps implementation

---

lading/src/blackhole.rs
lading/src/blackhole/http.rs
lading/src/blackhole/splunk_hec.rs
lading/src/blackhole/sqs.rs
lading/src/blackhole/tcp.rs
lading/src/blackhole/udp.rs
lading/src/blackhole/unix_datagram.rs
lading/src/blackhole/unix_stream.rs
lading/src/generator.rs
lading/src/generator/file_gen.rs
lading/src/generator/file_gen/logrotate.rs
lading/src/generator/file_gen/traditional.rs
lading/src/generator/file_tree.rs
lading/src/generator/grpc.rs
lading/src/generator/http.rs
lading/src/generator/procfs.rs
lading/src/generator/splunk_hec.rs
lading/src/generator/tcp.rs
lading/src/generator/udp.rs
lading/src/generator/unix_datagram.rs
lading/src/generator/unix_stream.rs
lading_payload/src/block.rs
lading_payload/src/lib.rs
lading_payload/src/splunk_hec.rs

This allows `lading::config` and `lading_payload::config` to be `Serialize`d.
I configure lading in code, want yaml.

Adds serde Serialize derive to lading_payload::config and lading::config

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml
lading/src/observer/linux.rs

In the linux observer, in addition to the rss and similar memory metrics we already compute, now compute the working set of the matching cgroup. The value is computed using a similar heuristic as kubernetes.
Better understand of the impact of agent changes (especially related to the single agent binary project).

[SMPTNG-183] Compute and report working set for each process

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

This release includes parsing of cgroup data to get working set memory. See #808 for details.

Release lading 0.20.8

---

lading_payload/src/dogstatsd.rs

In #813 I introduced new validation accidentally that asserted there must be tags present, this removes that incorrect assertion.

Removes incorrect assertion that tags must be present

---

lading_payload/src/dogstatsd/common/tags.rs

Utilize rust literal typing.
Avoid a cast.

Use usize literal instead of casting

---

lading_payload/src/dogstatsd.rs

Adds a constructor.
fields are private, so need a constructor to create custom version.

Adds constructor for ValueConf

---

lading/src/target_metrics/prometheus.rs

This commit fixes a bug where blank prometheus lines would cause the target scraper to crash. We now skip empty lines entirely.

Do not attempt to parse blank prometheus lines

---

lading/src/observer/memory.rs

Removes `expect` in favor of `?` for situation where `/proc` file could go away due to process exiting.
Fixing this panic
```
thread 'tokio-runtime-worker' panicked at lading/src/observer/memory.rs:359:14:
Failed to read contents into string: Os { code: 3, kind: Uncategorized, message: "No such process" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Removes expect from memory file region reading

---

.github/workflows/check-changelog.yml

`exit 0` does not prevent later steps from running, this refactors to only run the later steps if the `no-changelog` label was not present.
Fixing a bug in the CI enforcement.

Correctly blocks later steps from running if no-changelog label is present

---

lading/src/generator.rs
lading/src/generator/passthru_file.rs

This adds a new type of generator that takes the configured payload variant and writes the data out to a file on disk.
That's it.
Helpful to see the final payload output without having to pipe through `socat` or similar.

Adds generator that writes to a file on disk instead of socket/stream/etc

---

lading/src/generator/passthru_file.rs

Follow up to the passthrough file generator that was implemented in #824 
This file can get real big if we append to it, I got up to 24gb before I realized my mistake.

Truncates file while opening instead of appending

---

CHANGELOG.md
lading_payload/src/block.rs

Adjusts the block-filling function to effectively retry blocks that could not be filled on a first try.
This works because the `rng` will have a different state for the retried fill operation, and it has a chance to succeed.
Lading currently vastly under-generates payload data depending on the variant's configuration. This is not visible in the "throughput" that lading can produce, as it simply loops through the generated blocks.
For payloads where the content has semantic meaning, this means that the user-specified semantic meaning is lost, or at least not what the user specified.

SMPTNG-258: Fixes fixed-block-cache block generation to always fill requested block-chunks

---

Cargo.lock

Updates `mio` to avoid a security vuln.
Cargo-deny informed me of RUSTSEC-2024-0019 on a different PR.

Updates mio due to RUSTSEC-2024-0019

---

CHANGELOG.md
Cargo.lock
lading_payload/Cargo.toml
lading_payload/src/block.rs
lading_payload/src/dogstatsd.rs

When generating the block chunks that will be filled with a payload, instead of attempting to maintain even weightings of the block sizes, freely re-use them as needed to provide more capacity in the block chunks.
This also provides useful warnings when the payload cannot be fulfilled as written, eg:
```
2024-02-29T22:21:42.155929Z  WARN lading_payload::block: Failed to construct chunks adding up to 100 MB. Chunks created have total capacity of 10.24 MB. 89.76 MB unfulfilled. Max capacity of chunks was hit, consider making block sizes larger to fit more data.
```
User asked for a certain amount of data, lets try harder to fulfill their request.
Note currently based on #828

SMPTNG-259: Improve block chunk generation by re-using block sizes freely

---

CHANGELOG.md
lading_payload/src/block.rs

Block generation is at the heart of the lading payload generation, and unfortunately it is easy to specify configurations that will not "fill" to the desired capacity.
This increases the number of "chunks" that the data is split across in an attempt to remove rough edges.
Specifically, this helps with a case where a user specifies a large "pre-gen-cache-size", but only small "block sizes". It is usually impossible to fill the full cache if only tiny blocks are available.

Increase the max blocks by 4x

---

Cargo.lock
Cargo.toml
lading/Cargo.toml
lading/src/generator/grpc.rs
lading/src/generator/http.rs
lading/src/generator/passthru_file.rs
lading/src/generator/splunk_hec.rs
lading/src/generator/tcp.rs
lading/src/generator/udp.rs
lading/src/generator/unix_datagram.rs
lading/src/generator/unix_stream.rs
lading_payload/Cargo.toml
lading_payload/src/block.rs

Refactors the generators that take in `block_sizes` as an argument and extracts that logic and default to a single location in the code.
Simplify my next set of changes and de-duplicate the code.

De-duplicate block sizes

---

lading/src/common.rs

Adds the path that caused an `expect` to fail.
After:
```
thread 'tokio-runtime-worker' panicked at lading/src/common.rs:60:17:
Full directory path does not exist: /captures/target.stdout.log
stack backtrace:
0: rust_begin_unwind
```
(before the path was not present)

Adds the specific path that caused a failure

---

lading_payload/src/block.rs

Changes how block sizes are printed to logs.
Also pushes the verbosity to `WARN` for an incomplete block cache generation.
Before:
```
2024-03-05T22:35:50.596725Z  INFO lading_payload::block: Generator using user-specified block sizes: [
Byte(
1000,
),
Byte(
2000,
),
Byte(
3000,
),
]
2024-03-05T22:42:46.910944Z  INFO fixed{max_chunks=16384 payload="dogstatsd"}:construct_block_cache_inner: lading_payload::block: Block cache constructed. num_blocks=16384 filled_byte_sum=20428667 capacity_sum=32767000
```
After:
```
2024-03-05T22:44:33.696084Z  INFO lading_payload::block: Generator using user-specified block sizes: [Byte(1000), Byte(2000), Byte(3000)]
2024-03-05T23:03:34.836494Z  WARN fixed{max_chunks=16384 payload="dogstatsd"}:construct_block_cache_inner: lading_payload::block: Filled 20.43 …
```

Block construction cleanup

---

lading/src/generator/grpc.rs
lading/src/generator/http.rs
lading/src/generator/passthru_file.rs
lading/src/generator/splunk_hec.rs
lading/src/generator/tcp.rs
lading/src/generator/udp.rs
lading/src/generator/unix_datagram.rs
lading/src/generator/unix_stream.rs
lading_payload/src/block.rs

When a generator is requesting the block sizes from the user's config, the given generator may now optionally specify a maximum block size.
UDP datagrams have a hard size limit.

Adds max block size to block getter

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

Updates the lading version and changelog.
Preparing to release 0.20.9

Bumps version to 20.9 prepping for release

---

.github/dependabot.yml

Enables dependabot for github actions workflows
Keep gh actions up to date.

Adds github actions to dependabot

---

CHANGELOG.md
lading_payload/src/dogstatsd.rs
lading_payload/src/dogstatsd/metric.rs

Adds a config option to the dogstatsd generator to prepend a fixed string to each metric name.
Compatibility with an older benchmarking platform that needs this to filter things out.

Adds an optional way to prefix metrics with a special string

---

lading_payload/src/dogstatsd/metric.rs

Removes an erroneous `.`.
In #845 , I added support for an optional dogstatsd metric name prefix, however I accidentally duplicated the prefix separator.
`smp..jvTFhKcDf2bjDdgf4rTQt5` is the incorrect current behavior

prefix already contains a '.' separator, no reason to duplicate it

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

Updates changelog and cargo version for lading 0.20.10
Very small release, main motivation is to have a proper `latest` container build now that #844 has gone in.

Prepares the release of lading 0.20.10

---

.github/dependabot.yml

For `dependabot` pull requests updating GitHub Actions (not `cargo` crates), a changelog entry should not be required. Adding a `no-changelog` label to such pull requests should make merging those pull requests easier. This commit automatically adds `no-changelog` label to those pull requests.
Make it easier to approve & merge some `dependabot` pull requests.
Lack of a `no-changelog` label has caused pull requests #847, #849, #850, #851, and #858 to fail the changelog check in CI, so that label needed to be added to those pull requests.
I could see a counterargument to merging this pull request for some of the GitHub Actions we use to build `lading` in CI and package releases because updates to some of the Actions we use might affect the binaries we release (e.g., changes to …

dependabot actions update: add no-changelog label

---

lading_payload/src/block.rs

Provides a fix for the issue that proptest found in https://github.com/DataDog/lading/pull/861
The issue here lies with the fact that this test is trying to fill a 100byte block using the `json` generator, however the json generator randomly generates messages, so if they are too big, it simply tries again.
The threshold for "trying again" is quite low and therefore this issue is hit regularly with a 100byte block.
Increasing the block size to 1000 preserves the intent of the test while recognizing that small blocks are hard to generate JSON for.

Fix for PropTest failure in block construction

---

lading_payload/proptest-regressions/block.txt

This commit adds a failing case to the `proptest` cases for `block::test::construct_block_cache_inner_fills_all_blocks` in `lading_payload`.
Test failure occurred in testing of #847; see https://github.com/DataDog/lading/actions/runs/8336453710/job/22813606919?pr=847.
See above.
n/a

block: add failing case to proptest cases

---

CHANGELOG.md
lading/src/captures.rs

When `now.elapsed()` is greater than 1 second In the capture manager's call to `std::thread::sleep`, the subtraction within that call will panic with an overflow. Using a saturating subtraction should clamp negative values to zero, thus preventing such an overflow.
Prevent panics in the capture manager.
SMPTNG-317.
The log line that precipitated this investigation was
```
05:48:42 CET | service:docker
thread 'capture-manager' panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/time.rs:933:31:
```
See https://github.com/rust-lang/rust/blob/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/time.rs#L927-L935 for the code snippet in the Rust standard library that emits the panic.

capture_manager: avoid overflow via saturating sub

---

lading_payload/src/lib.rs
lading_payload/src/opentelemetry_log.rs
lading_payload/src/opentelemetry_metric.rs
lading_payload/src/opentelemetry_trace.rs

SMPTNG-83: Removes shim for now-standard lib func

---

CHANGELOG.md
lading/src/captures.rs

Addresses a shutdown race that can occur where `record_captures` is called incorrectly after the experiment has shut down.
This can result in truncated `capture.json` result files.
Fixing a bug in capture writing.

Capture manager should check shutdown before attempting to record captures

---

CHANGELOG.md
lading/src/generator/unix_datagram.rs
lading_payload/src/block.rs

This commit avoids shearing Unix datagrams if they are not able to transmit in one shot. Likewise we limit the size of each datagram to 8,192 bytes, received wisdom from Datadog Agent.
REF SMPTNG-356

Do not shear datagrams

---

Cargo.lock
lading/Cargo.toml

This commit updates the `clap` dependency to 3.2 and drops the feature flags that bring in atty. This later crate is unmaintained and is dinging our `cargo-audit` runs.

Update clap to 3.2

---

CHANGELOG.md
lading_payload/src/procfs.rs

Bugfix for the procfs generator - the `comm` field should be wrapped in parenthesis.
From the manpage:
/proc/pid/stat
...
(2) comm  %s
The filename of the executable, in parentheses. Strings longer than TASK_COMM_LEN (16) characters (including the terminating null byte) are silently truncated.  This is visible whether or not the executable is swapped out.
https://github.com/DataDog/smp-dogfooding/pull/13#issuecomment-2025938017
It's unclear how the process agent experiments have functioned at all - this bug will reliably crash the gopsutil code. It seems likely there's a race condition or some unexpected logic that allows process agent experiments to pass enough of the time for jobs to pass. (It could also indicate something incorrect in the SMP system.)

procfs generator: wrap `comm` in parens

---

lading/src/bin/lading.rs
lading/src/captures.rs
lading/src/signals.rs

This commit allows peers of the `Phase` to signal to the signaler that they have not yet completed their work. We achieve this by keeping a tally of the total number of peers that have called `register` -- a new function -- and require that each peer maintain a `Token` which on drop adds permits to a new semaphore. On the signaler side if the number of peers equals the number of permits in the ack'ing semaphore all registered peers have exited.
REF SMPTNG-356

Allow peers to signal Phase hold

---

CHANGELOG.md
Cargo.lock
integration/sheepdog/src/lib.rs
lading/Cargo.toml
lading/src/config.rs
lading_payload/src/block.rs

This commit adjusts the default block mechanism to be 'streaming' rather than
fixed. This resolves a problem where blocks -- needed to feed the throttle --
may not always sum up to the pre-constructed size that users configure.
REF [SMPTNG-356](https://datadoghq.atlassian.net/browse/SMPTNG-356)
[SMPTNG-356]: https://datadoghq.atlassian.net/browse/SMPTNG-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Streaming is the default block mechanism

---

CHANGELOG.md
lading/src/bin/payloadtool.rs
lading/src/config.rs
lading/src/generator/file_gen/logrotate.rs
lading/src/generator/file_gen/traditional.rs
lading/src/generator/grpc.rs
lading/src/generator/http.rs
lading/src/generator/splunk_hec.rs
lading/src/generator/unix_datagram.rs
lading/src/generator/unix_stream.rs
lading_payload/src/block.rs

This commit removes the streaming cache method in favor of the line of work being pursued in #886. We introduced streaming to work around the inability of lading to pack its cache space but the downside of streaming is the race it requires between the generator -- fast -- and the payload creator itself -- slow. This race is always eventually lost by the payload creator and so streaming can never sustain its throughput goals, except at a very low level.
Sharp edge, that.

Remove streaming cache method

---

CHANGELOG.md
integration/sheepdog/src/lib.rs
lading_payload/src/block.rs

This commit improves the 'pack' of our block construction by allow for dynamic block sizes based around the user-provided block sizes. The key insight here is that users don't _really_ care about the block sizes and in practice they are not obeyed: serialized blocks vary depending on the format. They're an abstraction leak. We therefore dynamically build blocks, keeping track of the minimum floor for a given serialization format and searching both 20% more and less on either size of the user-configured blocks.

Allow for dynamic block sizes in block construction

---

CHANGELOG.md
lading/src/bin/payloadtool.rs
lading/src/config.rs
lading/src/generator/file_gen/logrotate.rs
lading/src/generator/file_gen/traditional.rs
lading/src/generator/grpc.rs
lading/src/generator/http.rs
lading/src/generator/passthru_file.rs
lading/src/generator/splunk_hec.rs
lading/src/generator/tcp.rs
lading/src/generator/udp.rs
lading/src/generator/unix_datagram.rs
lading/src/generator/unix_stream.rs
lading_payload/src/block.rs

This PR follows up from #886 and removes the block configuration entirely, preferring instead to allow the users to configure a maximum block size. This is intended to simplfy the lading implementation and drive it closer to how users make use of lading in practice.

Remove explicit blocks

---

CHANGELOG.md
lading_payload/src/dogstatsd.rs

Bugfix; dogstatsd config ranges generated values using an exclusive range rather than inclusive range.

Dogstatsd: generate values that include the max of inclusive config ranges

---

CHANGELOG.md
lading/src/bin/lading.rs

During startup, lading now prints what version it is. 
Disambiguate logs from clusters that may be running different versions of the SW.

Prints version of lading in startup msg

---

CHANGELOG.md
lading/src/bin/lading.rs

Removes the `experiment_started` pause before installing the prometheus metrics registry.
We never noticed because capture files don't have this, and prometheus is basically only used in local development.

Removes incorrect pause before installing prom metrics registry

---

CHANGELOG.md
lading/src/codec.rs

Adds support for `zstd` encoded payloads in the HTTP blackhole
Support load generated by Agent's new zstd compressor.

Add zstd blackhole support

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml
lading/src/target.rs

This commit introduces the ability for the user to specify a container to act as target, by name, rather than by PID. The `bollard` crate is introduced to communicate with the docker server running on a default socket.
Give lading the ability to monitor docker containers.

Allow lading to watch a container as target

---

CHANGELOG.md
lading/src/bin/lading.rs

This commit adds a new flag that allows the user to specify an effectively infinite experiment duration. The exact value will vary by system but 584,942,417,355 years should be the more common value on modern systems.

Allow for effectively infinite experiment duration

---

lading/src/bin/lading.rs

Adds error handling by exiting lading when the `Observer` hits an error condition

Observer errors are now fatal

---

CHANGELOG.md
Dockerfile
lading/src/blackhole/http.rs
lading/src/config.rs
lading/src/generator/file_gen/logrotate.rs
lading/src/generator/file_gen/traditional.rs
lading/src/generator/file_tree.rs
lading/src/generator/grpc.rs
lading/src/generator/process_tree.rs
lading/src/generator/splunk_hec/acknowledgements.rs
lading/src/generator/tcp.rs
lading/src/generator/udp.rs
lading/src/observer/linux.rs
lading/src/target.rs
lading_payload/proptest-regressions/dogstatsd/common/tags.txt
lading_payload/src/dogstatsd.rs
lading_payload/src/lib.rs
lading_payload/src/procfs.rs
lading_payload/src/splunk_hec.rs
lading_payload/src/trace_agent.rs
rust-toolchain.toml

Updates the rust version used in this project. 
Also updates the debian base-image version for the docker base.

Update to rust 1.79.0

---

Cargo.lock
Cargo.toml

Switches metrics-rs family crates to a released version instead of pinning to a git commit.
The UDS-based prometheus exporter was released in a stable version.

Updates metrics-rs crates to latest released versions

---

lading/src/observer/linux.rs

This commit removes the `cgroup` label from Linux observer metrics as on some systems this value is essentially random, polluting the cardinality of metrics.

Remove `cgroup` label from Linux observer metrics

---

CHANGELOG.md
lading/src/observer/memory.rs

This fixes 2 bugs in the smaps parsing logic and makes 1 simplification.
1. Simpler method of reading smaps to a string, the size-hinting should be done by stdlib
2. A smaps region (VMA) can have varying hex address lengths, this was not properly accounted for
3. The logic to split an smaps file into individual memory regions (VMAs) needs to only match address-range looking things that appear at the beginning of the line.
Inaccurate `/proc/[pid]/smaps` data.

Improve smaps parsing support

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

This commit is the release of 0.22.0 version of lading. We have improved lading's ability to operate in a container ecosystem, exposing telemetry over UDS and by allowing a target to be specified by container name and enable effectively infinite duration experiments.
REF SMPTNG-441

Cut lading 0.22.0

---

.github/dependabot.yml

This commit mimics the behavior we see in github-actions PRs. It relieves a mechanical tedium on human reviewers of dependabot's PRs.

Add 'no-changelog' to dependabot cargo PRs

---

CHANGELOG.md
lading/src/target_metrics/expvar.rs
lading/src/target_metrics/prometheus.rs

This PR adds another configuration option to prometheus and expvar target metrics enabling a user to tag all the metrics coming from that configuration with optional additional labels
```
target_metrics:
- prometheus: #process agent telemetry 
uri: "http://127.0.0.1:6062/telemetry"
tags:
sub_agent: "process"
- prometheus: #core agent telemetry
uri: "http://127.0.0.1:5000/telemetry"
tags:
sub_agent: "core"
```
Currently in lading we could configure several prometheus endpoints to listen on to collect target metrics. In the example case of the agent being the target we could configure separate prometheus target metrics to get the internal telemetry of different sub agents. This issue is that when we do this there are some duplicate metrics across the sub agents. For example both the core …

Enable tagging of target metrics from prometheus and expvar endpoints by sub-agent name 

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

This commit is the release of 0.23.0 version of lading. We have added the ability to tag prometheus and expvar metrics with user defined tags.
[SMPTNG-422](https://datadoghq.atlassian.net/browse/SMPTNG-422)
https://github.com/DataDog/lading/pull/941
[SMPTNG-422]: https://datadoghq.atlassian.net/browse/SMPTNG-422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cut lading 0.23.0

---

examples/lading.yaml

This was missed when we deprecated block_sizes from configs.

remove block sizes from examples

---

lading/src/bin/captool.rs

Corrects the 'zstd' handling of captures
Somehow I flipped this 🤷

Corrects captool's zstd handling

---

lading_signal/src/lib.rs

Optional PR. This may work around failing UDS experiments.
`Watcher::recv()` is cancelled and called again on every request sent by the unix datagram generator and likely others. This is incorrect for the new signaling mechanism and should be adjusted. This PR will eliminate a source of log spam that may be causing experiments to fail to complete.

Don't instrument `Watcher::recv()`

---

lading_signal/src/lib.rs

It's my goal to re-introduce the distinction between registered and unregistered `Watcher` instances. I want to be very careful about the order of changes, else it will be hard to debug when the loom models ding us.
REF SMPTNG-455

Migrate peer logic management fully into `decrease_peer_count`.

---

deny.toml

This check is the most noisy hit we get from cargo-deny. Most often it's for a dependency of one of our dependencies, not something we can do anything about.

Make unmaintained crates a warning

---

.github/workflows/audit.yml

cargo audit runs are currently only visible within the execution logs due to the lack of this permission.
eg, from
https://github.com/DataDog/lading/actions/runs/10726172279/job/29745638706#step:3:128
```
Warning: 1 warnings found!
Found 1 unmaintained
Error: Unable to publish audit check! Reason: HttpError: Resource not accessible by integration
Warning: It seems that this Action is executed from the forked repository.
Warning: GitHub Actions are not allowed to use Check API, when executed for a forked repos. See https://github.com/actions-rs/clippy-check/issues/2 for details.
```
surface cargo-audit failures in a more noticeable way

adds check write perm to audit action

---

lading_signal/Cargo.toml
lading_signal/src/lib.rs

This commit extends the "registered" notion to have a distinct
implementation from something that is not "registered".
REF SMPTNG-455

Clarify "registered" notion

---

lading/src/bin/lading.rs
lading/src/captures.rs
lading/src/generator/file_gen/logrotate.rs
lading/src/generator/file_gen/traditional.rs
lading/src/generator/splunk_hec.rs
lading/src/generator/unix_datagram.rs
lading/src/target_metrics/prometheus.rs

This commit adjusts lading so that only the CaptureManager has a registered Watcher. We wish to signal and exit the main loop before confirmed shutdown except in the case of the capture writer.
REF SMPTNG-455

Adjust only CaptureManger to register a Watcher

---

lading/src/bin/lading.rs
lading/src/blackhole/http.rs
lading/src/blackhole/splunk_hec.rs
lading/src/blackhole/sqs.rs
lading/src/blackhole/tcp.rs
lading/src/blackhole/udp.rs
lading/src/blackhole/unix_datagram.rs
lading/src/blackhole/unix_stream.rs
lading/src/generator/file_gen/logrotate.rs
lading/src/generator/file_gen/traditional.rs
lading/src/generator/file_tree.rs
lading/src/generator/grpc.rs
lading/src/generator/http.rs
lading/src/generator/passthru_file.rs
lading/src/generator/process_tree.rs
lading/src/generator/procfs.rs
lading/src/generator/splunk_hec.rs
lading/src/generator/tcp.rs
lading/src/generator/udp.rs
lading/src/generator/unix_datagram.rs
lading/src/generator/unix_stream.rs
lading/src/inspector.rs
lading/src/observer.rs
lading/src/target.rs
lading/src/target_metrics/expvar.rs
lading/src/target_metrics/prometheus.rs
lading_signal/src/lib.rs

This commit resolves a long-standing confusion as to whether recv
should be called multiple times and to what will happen if it is.
We resolve now to only allow it to be called once, requiring a future
from recv to be pinned on the stack.
SMPTNG-455

Make `Watcher::recv` take ownership

---

CHANGELOG.md
lading/src/bin/lading.rs

Wait for the target PID broadcast before starting the warmup timer. This indicates that the target is running. I decided not to use a standard lading signal because the PID broadcast is already setup and serving the same purpose.
This fixes an issue where the warmup period is finishing before the target is fully started when container targeting is used.

Don't start warmup period until target is running

---

lading/src/bin/captool.rs

Fix zstd-by-extension detection in captool.
Make captool correctly detect capture format by extension name.

captool: fix zstd detection

---

lading/src/bin/captool.rs

Add min/max calculations to captool's metrics summary output.
Share more details about series being inspected.

captool: add min/max to metrics summary

---

CHANGELOG.md
lading/src/bin/lading.rs
lading/src/captures.rs
lading/src/target.rs

Make the capture manager wait for the target to be running before starting to spin.
This stops fetch index from increasing while the target container is starting up. Fixes a bug we saw where the data we're interested in would start at fetch index 30-50 in captures. That caused some amount of havoc with fetch-index based warmup.
Adds a target-running signal alongside the existing target PID broadcast. This clarifies the intent of the receiver code.

Wait for target to be running in capture manager

---

Cargo.lock
lading/Cargo.toml
lading/src/bin/captool.rs
lading/src/captures.rs
lading_capture/src/json.rs

Convert captool to stream input files rather than reading them in entirety.
This is not much faster, but ought to have much lower peak memory usage.

captool: use streaming readers

---

lading/src/bin/captool.rs

Print the metric kind in captool and show an error if no metrics were found.
Understand where we're processing counters incorrectly.

captool: print the metric kind

---

CHANGELOG.md
lading/src/blackhole/http.rs

This commit allows lading HTTP blackhole to delay a response to
the sender, intention being to allow for the simulation of latent
network connections to a sink location.

Allow blackhole to delay response

---

lading_signal/src/lib.rs

In practice the only use lading puts tokio instrumention to is logging and
while it can be useful in development it ends up really clogging logs,
especially the enter exit etcs.
Commit is intended to tidy up logs.

Remove lading_signal tokio instrumentation

---

lading/src/bin/lading.rs
lading/src/generator/file_gen/logrotate.rs

This commit removes every span event by configuration. It's not useful information
in logs per se and really does muddy up any analysis of the logs by a human.

Remove span event log churn

---

lading/src/generator/file_gen/logrotate.rs

This commit adjusts the logic we used to construct log file names to avoid
dropping parent paths. I had, apparently, terribly misunderstood the logic of
PathBuf when pushing and the previous code could land log files outside of
`root` config setting.

Correct logrotate error when creating files with complex directories

---

lading/src/generator/file_gen/logrotate.rs

This commit drops `fp` whenever we flush it and overwrite `fp`. This
is implied by the overwrite, of course, but I found myself wondering
about when exactly this operation took place, so now it's explicit.

Drop file handle just to be extra certain

---

lading/src/generator/file_gen/logrotate.rs

As it says on the tin, I no longer need this info! call and it just
pollutes the logs without need at this point.

Remove debugging `names` info! call

---

lading/src/generator/file_gen/logrotate.rs

I'm working on a theory that lading file-gen runs fail because one of the IO
operations that takes place is failing and the error is being silenlty eaten.
Unclear if true. This commit also converts any panics to error returns.

Add error! logs around logrotate errors

---

lading/src/generator/file_gen/logrotate.rs

In my downstack PR I discovered that in fact we have some IO error happening
in practice although exactly which one who can say. This PR attempts to say.
I've gone through and made every error very explicit and where possible added
the paths being acted on.

Make IO errors paintful explicit in logrotate generator

---

CHANGELOG.md
lading/src/generator/file_gen/logrotate.rs

This commit removes a bug in the logrotate rotation mechanism where
renames would cause the child generator crash if more than one historical
copy of a log file was kept on disk.

Correct rotation bug in logrotate

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

This release contains several quality of life improvements around file generation and allows for the modeling of HTTP sinks with latency. The unused protobuf version of `lading_capture` is removed.

Release lading 0.23.3

---

lading/src/bin/captool.rs
lading/src/observer/linux.rs

Runs `cargo fmt` on the `lading` crate.
I'm making a different PR, but it's tedious disable `cargo fmt` and format manually.

Run cargo fmt

---

CHANGELOG.md
lading/src/target_metrics/prometheus.rs

Simply discard invalid counter and gauge values instead of panicking.
Discovered when fixing #1039 
None
None

[target_metrics] Avoid panicking on an invalid counter or gauge value

---

.github/workflows/audit.yml
.github/workflows/check-changelog.yml
.github/workflows/ci.yml
.github/workflows/container.yml
.github/workflows/release.yml

To silence some Datadog security warnings, this commit pins all of the GitHub Actions we use to SHAs, via
[`frizbee`](https://github.com/stacklok/frizbee)
```shell
GITHUB_TOKEN="$(gh auth token)" frizbee actions \
"$(git rev-parse --show-toplevel)/.github/workflows"
GITHUB_TOKEN="$(gh auth token)" frizbee actions \
"$(git rev-parse --show-toplevel)/.github/actions"
```
Without authentication, `frizbee`'s GitHub API requests may be rate-limited, which causes silent failures, and `frizbee` may fail to replace some version tags with SHAs.
This Datadog security [notification](https://github.com/DataDog/lading/pull/1036#discussion_r1799023703).
SMPTNG-492.
Frizbee is installable via
```shell
brew install frizbee
```

github actions: pin to SHAs

---

.github/workflows/audit.yml
.github/workflows/check-changelog.yml
.github/workflows/ci.yml
.github/workflows/container.yml
.github/workflows/release.yml

- Adds full version strings for any pinned GitHub Actions that had a `# v{major}` comment. Changing this comment to a `# v{major}.{minor}.{patch}` comment seems to make Dependabot update pull requests easier to read, and Dependabot is more likely to keep the comment in sync with the hash in the latter format.
- Adds an `actionlint` job, similar to that in the Single Machine Performance repo.
- Adds a job to check that all used Actions are pinned to SHAs.
- Replaces `actions-rs/audit-check` with `actions-rust-lang/audit` because the former has been archived and is read-only since 2023-10-13.
Avoid introducing any new uses of GitHub Actions that aren't pinned to SHAs, for security reasons.
SMPTNG-492.
This pull request uses a newer version of `actionlint` than Single Machine Performance.

ci: add jobs to lint GitHub Actions and check all used actions are pinned to SHAs

---

CHANGELOG.md
lading/src/generator/http.rs
lading/src/generator/splunk_hec.rs
lading/src/generator/splunk_hec/acknowledgements.rs

Send the HTTP Host header for the HTTP generator and the Splunk generator.
The Host header is required for compliant HTTP traffic. Send it so that standard web servers will properly receive HTTP requests.
Note that there are two other places in the code that this `set_host(false)` method is used ([1](https://github.com/DataDog/lading/blob/4f7ec01c17fcf74abcf55cc9d9226a08c6155ff3/lading/src/generator/splunk_hec.rs#L251)) ([2](https://github.com/DataDog/lading/blob/4f7ec01c17fcf74abcf55cc9d9226a08c6155ff3/lading/src/generator/splunk_hec/acknowledgements.rs#L92)). I'm leaving them as is because I'm not familiar with Splunk and whether it needs this behavior.
UPDATE: Commit 9d3e627534d964 now removes the `set_host(false)` call from Splunk also, so Host headers are added by `hyper` everywhere.

Send the HTTP Host header for the HTTP generator.

---

lading_payload/src/fluent.rs

Optimizes a hashmap during fluent log generation
Fluent payload is v slow.

Pre-allocates the hash map for medium perf wins (5s vs 6.2s)

---

lading/src/bin/payloadtool.rs
lading_payload/src/block.rs

Adds `info` level logs at increasing in-frequency during block generation.
Some of the variant generations can be pathologically slow. We should fix those cases, but right now there is no useful feedback and lading just appears "stuck" during payload generation.
I could be convinced to do a straight up "status update once a minute" instead of fibonacci sequence

Adds progress indicators for slow block generation

---

.github/actions/install-fuse/action.yml
lading/src/bin/logrotate_fs.rs
lading/src/generator/file_gen/model.rs

This commit retains the use of a stateless tick in the model but
allows for the filesystem to report times in systemtime. This
resolves a problem where all times were previously reported by the
filesystem as being UNIX_EPOCH even though the model kept track of
time.

Update file timestamps to reflect real systemtime

---

.github/actions/install-fuse/action.yml
lading/src/generator/file_gen/model.rs

This commit ensures that a Node has advance_time called on it when
the filesystem calls getattr. If this is not done repeat calls to ls,
for instance, will show the file size not changing although a call to
read would.

Ensure file size updates due to getattr

---

lading/src/bin/payloadtool.rs
lading/src/generator/file_gen/model.rs
lading_payload/src/block.rs

This commit exposes a `read_at` on the block cache allowing callers to
read the same data from offset X over and over again. This means that
when we expose data from a block cache in the logrotate filesystem we
are able to correctly do `wc -l` and similar.

Allow readers to read consistently

---

lading/src/bin/logrotate_fs.rs
lading/src/generator/file_gen/model.rs

This commit avoids an extra name lookup but using the name of an inode
as its key in the directory. This will be slightly complicated by
rotating files depending on how I do them but it is a win in terms
of code simplification now.

Avoid extra name lookup

---

lading/src/generator/file_gen/model.rs

I'm working now to get rotation logic introduced in State. The first
step is to move time advancement to a single place in State -- the
advance time function -- although reads and what not in File still
induce advances I think. All will be smoothed out eventually.

Adjust time advancement to be done by State

---

lading/src/bin/logrotate_fs.rs
lading/src/generator/file_gen/model.rs

This commit places the last few bits needed for file rotation. At this point I intend to add a list of static names to index into and then after that, expand State::advance_time to perform rotations.

Add component pieces for rotation

---

lading/src/bin/logrotate_fs.rs
lading/src/generator/file_gen/model.rs

All File names are now present in a pre-defined pool that is stored in State. Each Directory node continues to hold its own name.

Move names into a pre-created name pool

---

Dockerfile
lading/src/generator/file_gen.rs
lading/src/generator/file_gen/logrotate_fs.rs
lading/src/generator/file_gen/logrotate_fs/model.rs

This commit migrates logrotate_fs to be a generator and not a stand-alone binary. While I think it is interesting to consider logrotate_fs as a user defined generator that's more of a rig that needs to be developed than I would like to for this project.

Make logrotate_fs a generator

---

lading/src/generator/file_gen/logrotate_fs.rs

This commit does not change the mechanism but it does largely improve
documentation.

Tidy up some clippy allows in logrotate_fs

---

examples/lading-logrotatefs.yaml
lading/src/generator/file_gen/logrotate_fs.rs
lading/src/generator/file_gen/logrotate_fs/model.rs

This commit involves minor tweaks to the logrotate_fs to improve logging
and the configuration of said generator. Also I include an example
config.

Configuration and logging improvements to logrotate_fs

---

lading/src/generator/file_gen/logrotate_fs/model.rs

This commit adjusts the model to simulate every tick between the previous
moment time was advanced and the current moment. This avoids errors where
files grow well past the size they should -- demonstrated now with an
additional model property.

Simulate all ticks, not just some

---

examples/lading-logrotatefs.yaml
lading/src/generator/file_gen/logrotate_fs.rs
lading/src/generator/file_gen/logrotate_fs/model.rs

This commit removes allocations in the FUSE component that don't
need to exist and adjust the interior hashmap to use FxHashMap,
avoiding a secure hash in favor of a fast one. Also, directories
now keep their children in a BTreeSet so that readdir is always
in the same order when called.

Avoid some allocations, hashes that aren't needed

---

lading/src/generator/file_gen/logrotate_fs.rs
lading/src/generator/file_gen/logrotate_fs/model.rs

For the sake of consitency, always update time when the state lock
is taken.

Uniformly advance time in logrotate_fs

---

lading/src/generator/file_gen/logrotate_fs.rs
lading/src/generator/file_gen/logrotate_fs/model.rs

This commit ensures that at startup the state does not start at an
arbitrary tick but at one synchronized with the logrotate_fs. In
practice this comes to the same thing -- today -- but it's an easy
bug to trip on in the future.

Make sure state starts at close to now tick

---

lading/src/generator/file_gen/logrotate_fs.rs

This commit allows the logrotate_fs to create its mountpoint in the
event that the user has not created the directory ahead of time.

Create mount-point in logrotate-fs start if it does not exist

---

Dockerfile

If the logrotate_fs generator is in use we must have fusermount3 in
the container. This commit adds this command to the container.

Install fuse3 in lading container

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

This commit releases lading 0.23.4, incorporating fixes for our prometheus
metrics scraping, the way our HTTP client presents itself via the host header
and adds a log rotation filesystem.

Release lading 0.23.4

---

CHANGELOG.md
lading/src/target.rs

In some cases docker will report that the pid of a new container is 0.
This is not a usable pid and we believe it is a race condition. Loop
around again in this even, logging.

Do not transmit pid 0 as the target pid

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

This commit addresses a bug in the lading target mechanism. In some cases pid 0 would be reported by docker as the pid of the watched container. We also now scope our release down to only the container artifact.

Release lading 0.23.5

---

lading/src/generator/file_gen/logrotate_fs/model.rs

This commit adds more information to the lost_bytes telemetry, intention
being to make it easier to debug under what conditions bytes are lost.
REF SMPTNG-517

Add more information to lost_bytes telemetry

---

Cargo.lock
lading/Cargo.toml
lading/src/generator/file_gen/logrotate_fs.rs

This supplants #1081. fuser added a `fh` argument to getattr which
we introduce and subsequently ignore.

Update to fuser 0.15

---

.github/actionlint.yml
.github/workflows/container.yml
Dockerfile

This commit replaces #1088 and attempts to build a lading multi-platform image by use of organization provided ARM native builders. Unsure if this'll work but I figure it's worth a shot.

Use native ARM builders for container builds

---

.github/workflows/ci.yml
CHANGELOG.md
Dockerfile
lading/Cargo.toml
lading/src/generator/file_gen.rs

Building logrotate_fs requires special libraries on OSX that are not generally needed by developers on that platform as logrotate_fs cannot run there sans a kernel module. As such, stick the generator behind a feature flag.

Set logrotate_fs behind a feature flag

---

deny.toml

There's really nothing we can do in the short-term about these
unmaintained cargo-deny errors other than keep our dependency
tree updated.

Ignore unmaintained errors

---

lading/src/generator/file_gen/logrotate_fs.rs
lading/src/generator/file_gen/logrotate_fs/model.rs

This commit allows State to track whether a file handle is valid for read etc
operations. Our GC mechanism keeps track of the open-handles but assumes the
correctness of callers, meaning if multiple calls to `release` are made at the
filesystem level a node may be GC'ed before its time.
The State now keeps a record of which FileHandles exist and whether they remain
valid, meaning the GC mechanism cannot be misled.
SMPTNG-531

Validate operations on FileHandles

---

CHANGELOG.md
lading/Cargo.toml

Enable http1 and http2 in the build. This looks like it will get us http2 functionality by default.
Incoming request.
[hyper 0.14.30 docs](https://docs.rs/hyper/0.14.30/hyper/)

Explicitly enable http1 & http2 in the build

---

Cargo.lock
lading/Cargo.toml
lading/src/bin/lading.rs
lading/src/observer/linux.rs
lading/src/target.rs

This commit updates procfs dependency to 0.17. #1096 is now redundant.

Update procfs to 0.17

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml
lading/src/captures.rs

This commit attempts the generational storage of metrics in the capture
recorder. I am patterning this work from metrics-prometheus-exporter and
I think I understand how this is wired up?
One thing of note gauges are now ints and not f64s although the interface
still requires f64 on the gauge! side. Unsure how that works out.

Attempt generational storage of capture metrics

---

CHANGELOG.md
lading/src/bin/lading.rs
lading/src/observer.rs
lading/src/observer/linux/procfs.rs
lading/src/target.rs

We previously had a mechanism that would allow the generators to back off
if the target was determined to be nearing a preconfigured memory consumption.
We decoupled this at some point -- I'm not sure when -- and then forgot to
remove the interface. It does not appear this was used in practice.

Remove target RSS_BYTE tracking

---

lading/src/observer/linux/procfs.rs

This commit removes the Gauge zero-set in the procfs sampler, relying now
on the work done in #1125 to expire metrics that are no longer written
to.

Rely on metrics registry to expire metrics

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml
lading/src/captures.rs
lading/src/observer/linux/cgroup/v2.rs
lading/src/observer/linux/procfs.rs
lading/src/observer/linux/procfs/memory/smaps.rs
lading/src/observer/linux/procfs/memory/smaps_rollup.rs

This commit expands the number of fields we parse from the smaps/smaps_rollup
files. I have not hooked these up yet to metrics emission but will in a follow-up
commit to this PR.

Expand smaps / smaps_rollup parsing

---

lading/src/observer/linux/procfs.rs

This commit removes a joinset in the inner polling loop of the procfs
sampler. The existence of the joinset makes calculation of total_pss,
total_rss more difficult and its unclear that there is a performance
boost by its existence.

Slim out joinset

---

lading/src/observer/linux/procfs.rs
lading/src/observer/linux/procfs/memory/smaps_rollup.rs

This commit adds collection of total PSS bytes for all processes from
smaps_rollup, adjusting total_rss_bytes to also be from the same source

total_rss_bytes and total_pss_bytes from smaps_rollup

---

lading/src/observer/linux/procfs.rs
lading/src/observer/linux/procfs/memory/smaps_rollup.rs

There is a bug in lading where gauge values for smaps_rollup, smaps
come through in the EiB range. The changes here are not a fix but they
don't hurt either and they're a good idea.

Avoid potential overflows

---

lading/src/captures.rs

This commit corrects a bug whereby the capture manager did not coerce the
u64 values up from the registry storage into their f64 representation, meaning
we reported out to captures comically huge values.
Much obliged to @tobz who spotted the bug.

Correct a coercion bug in capture manager

---

lading/src/observer/linux/cgroup.rs
lading/src/observer/linux/cgroup/v2.rs
lading/src/observer/linux/cgroup/v2/cpu.rs

This commit expands the cgroup sub-observer to inspect the CPU consumption of the target group, calculating a percentage utilization from this.
Resolves SMPTNG-385

Read CPU percentage from cgroup data

---

CHANGELOG.md
lading/src/observer/linux/cgroup/v2/cpu.rs
lading/src/observer/linux/procfs.rs

This commit adjusts the CPU percentages that make it to the captures
to be founded on cgroup data. This commit primarily removes code as
a result.
Resolves SMPTNG-385

Remove procfs CPU percentage

---

CHANGELOG.md
lading/src/observer/linux/cgroup/v2/cpu.rs

This commit introduces a millicore calculation of consumption and
limits into the cpu Linux observer. All data is sourced from cgroups.
REF SMPTNG-109

Introduce k8s style millicore CPU data

---

lading/src/blackhole/http.rs
lading/src/blackhole/splunk_hec.rs
lading/src/blackhole/sqs.rs
lading/src/blackhole/tcp.rs
lading/src/blackhole/udp.rs
lading/src/blackhole/unix_datagram.rs
lading/src/blackhole/unix_stream.rs
lading/src/captures.rs
lading/src/generator/file_gen/traditional.rs
lading/src/generator/grpc.rs
lading/src/generator/passthru_file.rs
lading/src/generator/tcp.rs
lading/src/generator/udp.rs
lading/src/generator/unix_datagram.rs
lading/src/generator/unix_stream.rs
lading/src/observer/linux/cgroup/v2/cpu.rs
lading/src/target_metrics/expvar.rs
lading/src/target_metrics/prometheus.rs

This commit corrects a bug where counter values -- integer -- were
converted to floats leading to odd capture data. I have also adjusted
our use of metrics to always use the macro, avoiding metric handles
that might cause a metric to not expire when it should.

Don't coerce counters to floats, avoid metrics handles

---

lading/src/observer/linux/cgroup.rs
lading/src/observer/linux/cgroup/v2/cpu.rs
lading/src/observer/linux/procfs.rs
lading/src/observer/linux/procfs/memory/smaps_rollup.rs
lading/src/observer/linux/procfs/stat.rs

This commit re-introduces per-process CPU data from /proc/{pid}/stat reusing the
same naming scheme from the cgroup sourced data, offset with stat. to avoid
summing issues in aggregations.
I have removed much of the stat code from the main procfs sample loop. The data
was either no longer used or is duplicated elsewhere. Some data could be
re-introduced if we desire by extending the poll loop in stat.rs.
I am continuing to remove more and more of our procfs crate integration. I
think, ultimately, we should be able to parse directly without the need of a
third-party dependency. That removal is near done now.

Re-introduce per-process CPU collection

---

lading/src/observer/linux/cgroup.rs
lading/src/observer/linux/cgroup/v2/cpu.rs

This commit corrects a similar bug to the one that I corrected in
the stats reader, originally copied from this point. Specifically,
we now store state that maintains the cgroup previous values needed
to calculate diffs over time.

Ensure cgroup CPU poller works with multiple cgroups

---

CHANGELOG.md
lading/src/bin/lading.rs
lading/src/captures.rs
lading/src/config.rs

This commit adjusts the capture metrics expiration so that it is by
default Duration::MAX and is a configurable setting. In the future we
will bring this value down, but this preserves behavior between lading
releases while still allowing for new capability.

Allow users to configure capture metrics expiration

---

lading/src/observer/linux/procfs.rs
lading/src/observer/linux/procfs/uptime.rs

This commit is a mechanical move of the function that reads uptime data
under the procfs/ module. It's intended to keep the code tidy.

Split reading of `/proc/pid/updtime` into module

---

CHANGELOG.md
lading/src/blackhole/http.rs

Adds the HTTP `path` that a request was sent to for the metrics that give insight into the blackhole-received data.
Datadog agent sends to many different endpoints, we observe spikes that don't have a clearly understood destination, this will help.
I omit the `query` parameters, which should limit the cardinality of these metrics, but this is still a technically unbounded metric tag, which isn't ideal. I wasn't able to come up with any ideas to bound the cardinality here without making this feature significantly less useful (ie, only record up to 1/2/3 path segments)

Adds path to metric labels for http blackhole

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

This release pulls significantly more data from cgroups v2 and also procfs smaps, makes generational storage available in the capture recorder and attempts to make builds on OS X easier if FUSE dependencies are not present.
Please see changelog for further details.

Release lading 0.25.0

---

lading/src/generator/file_gen/logrotate_fs.rs

We have some targets that look up wildcard files in the event they
exist on-disk. This causes a lot of ERROR spew in lading logs that
could otherwise be avoided.

Make failed lookups WARN not ERROR

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

This release reverts PR #1148. Unfortunately duplicate tags on the metrics `bytes_received` causes errors in an analysis tool that is on a more strict release schedule than lading itself. We will have to re-introduce this change at a later date.

Release lading 0.25.1

---

.github/workflows/container.yml

This commit makes sure our tag metadata is made to match across all the metadata extraction. The lack of this parity caused the release builds for 0.25.0 and 0.25.1 to fail to tag properly.

Multi-arch container takes the same tag meta

---

Cargo.toml
integration/ducks/Cargo.toml
integration/sheepdog/Cargo.toml
lading/Cargo.toml

This commit migrates all `tower` crate use to derive from the workspace.
This is intended to make updating tower easier.

Migrate all `tower` use to workspace

---

Cargo.lock
lading/Cargo.toml
lading/src/bin/lading.rs

This commit updates the clap crate in use by lading to the latest
release.

Update clap to 4.5

---

CHANGELOG.md
lading/src/blackhole/http.rs

This commit adjusts `bytes_received` to measure the bytes received over the wire
before decoding. This allows lading to make assertions about the efficacy of
compression by targets, matching the behavior of the other lading blackholes. We
preserve the decoded metric by renaming it `decoded_bytes_received`.

Adjust how `bytes_received` is calculated in the HTTP blackhole

---

CHANGELOG.md
Dockerfile

This commit updates the lading base OS from Debian bullseye to the
latest stable bookworm.

Update lading container base image

---

CHANGELOG.md
lading/src/blackhole/splunk_hec.rs

Similar to #1166 this commit adds a `decoded_bytes_received` so that the telemetry
from this blackhole matches the others in the project, measuring the raw/wire bytes
in `bytes_received`.

Adjust splunk_hec to distinguish decoded and raw bytes received

---

.github/workflows/container.yml
CHANGELOG.md
Cargo.lock
lading/Cargo.toml

This commit cuts  0.25.2. Minor changes are present here -- some telemetry changes, base OS image is updated -- and we believe now that the container images will be published properly.

Release 0.25.2

---

Cargo.toml
integration/ducks/Cargo.toml
integration/shared/Cargo.toml
integration/sheepdog/Cargo.toml

This commit migrates the `tonic` dependency to the workspace. Unfortunately
this leaves tonic-build still in shared/Cargo.toml but it's a start. Goal
here is to make upgrading tonic more achievable.

Migrate `tonic` to workspace

---

Cargo.lock
integration/ducks/Cargo.toml
integration/ducks/src/main.rs
integration/shared/Cargo.toml
integration/sheepdog/Cargo.toml
integration/sheepdog/src/lib.rs

This commit is peer to #1179 and takes an alternative approach: only
upgrade hyper et al in single spots in the project. This means we have
a mix of different hyper versions et al but it does compile at least.
This is a wretched mess. I couldn't make tower work in ducks so it's
dropped -- we'll need to add load shedding and concurrency control ourselves
if we want it -- and while it's cool that hyper is now a 1.0 crate I
really, really don't love that we depend on a small set of 0.1 crates
to get there. I don't know if I would rather just opt into axum or not,
although hyper at least will be a going concern in the ecosystem
with high probability.

Upgrade hyper, tonic et al only in ducks

---

Cargo.toml
integration/ducks/Cargo.toml
integration/shared/Cargo.toml
integration/sheepdog/Cargo.toml
lading/Cargo.toml

This commit re-unifies our crates at the workspace level, reversing a process begun
in #1181 in order to upgrade hyper et al in a feasible way.

Re-unify crates at workspace

---

lading/src/blackhole.rs
lading/src/blackhole/common.rs
lading/src/blackhole/http.rs
lading/src/blackhole/splunk_hec.rs
lading/src/blackhole/sqs.rs

This commit unifies the httpd bits of the blackholes, removing a duplicated loop in three places. The type logic here started out general and got gradually more concrete and there's scope to reduce duplication even further but I don't know that it's a pressing issue.

Unifty httpd in blackholes

---

lading/src/blackhole/common.rs
lading/src/blackhole/http.rs
lading/src/blackhole/splunk_hec.rs
lading/src/blackhole/sqs.rs

This commit introduces telemetry keeping track of the connection
limit for http blackholes and the current connection count. This is
desirable information for targets that wish to trade total connections
for other resources.

Instrument connection limit and current count for http blackholes

---

Cargo.lock
lading/Cargo.toml
lading_payload/fuzz/Cargo.lock

This dependency was not in fact used by this crate. We remove it for the
sake of tidiness.

Remove 'tower' dependency from lading/Cargo.toml

---

CHANGELOG.md
lading/src/observer/linux/cgroup/v2.rs

This commit introduces the parsing of v2 PSI metrics into lading.
We special-case memory.pressure, cpu.pressure and io.pressure to
be parsed.

Parse PSI cgroup v2 metrics

---

CHANGELOG.md
lading/src/generator/splunk_hec.rs
lading/src/generator/splunk_hec/acknowledgements.rs

Only requires ack id in Splunk HEC responses when acknowledgements are enabled.
`splunk_hec_to_splunk_hec_logs_noack` experiment in Vector is currently failing due to lading expecting ack responses and Vector not returning them. This error was previously hidden but exposed by https://github.com/DataDog/lading/commit/c38e915.
Open to thoughts on refactoring this. I took what seemed like the most straightforward path towards a fix.

fix(splunk_hec generator): Only require ack when acks enabled

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

This release adds cgroup v2 PSI metrics and the splunk-hec generator now only requires ackId if acknowledgements are enabled.

Release lading 0.25.4

---

CHANGELOG.md
lading/src/bin/lading.rs
lading/src/config.rs
lading/src/observer.rs

Historically the observer has been sampling at 1hz, although the
only place this was explicit was in lading bin. We now expose
`sample_period_milliseconds` to configure this rate. The default
remains one second.

Allow observer sample rate to be configured

---

CHANGELOG.md
lading/src/bin/lading.rs
lading/src/target_metrics.rs
lading/src/target_metrics/expvar.rs
lading/src/target_metrics/prometheus.rs

The existing `sample_period_milliseconds` config option is now used for the target metric scraping interval.
Oversight from #1217 , the observer metric collection should occur at the same rate as the target metrics are scraped.

'sample_period_milliseconds' changes target metric collection interval

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml
lading/src/target_metrics/expvar.rs

Adds support for https requests for scraping expvar. Currently I am allowing any certificate with no tls verification. This is most definitely a bad practice in general. For this specific use case it _may_ be fine. After testing this I should be able to pass in the pem path used for tls validation if we dont want to allow any certificate. 
Error seen in this [notebook](https://app.datadoghq.com/notebook/11124176/caleb-investigating-http-to-https-error?notebookType=rte)
Update as of Jan 22:
The change to set trace agents debug endpoint to https has been reverted for now so this change is not needed yet.
Update as of Jan 29:
The change has [landed](https://github.com/DataDog/datadog-agent/pull/33402). These errors will be present from now. I need to update expvar endpoint for quality gates …

Added support for https in expvar scraping

---

.github/workflows/release.yml

This reverts commit 58b098c392f99e663a0354e153e0682b4cf51d99.
Reverts - Bump [taiki-e/create-gh-release-action](https://github.com/taiki-e/create-gh-release-action) from 1.8.3 to 1.9.0.
1.9.0 has a bug where the github release fails to be created

Revert "Bump taiki-e/create-gh-release-action from 1.8.3 to 1.9.0

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

Updates changelog and cargo version for lading 0.25.5
Enable https scraping of expvars and also allow users to configure their sample rate

Release lading 0.25.5

---

Cargo.lock

Version bumped to avoid RUSTSEC-2025-0004

Update Openssl to .70

---

CHANGELOG.md
lading/src/target_metrics/prometheus.rs

Ignores counters and guages scraped over prometheus that have a NaN value.
Turns out NaN is a valid [constant](https://doc.rust-lang.org/std/f64/constant.NAN.html) of f64 so when we scrape prometheus endpoint and read a NaN value we try to set it as a gauge or counter. This is then translated to null in the capture file. null in the capture file causes `rouster-series-sender` to fail when submitting metrics
I am not 100% confident that this is all we need to handle all edges regarding NaN

Ignore metrics read over prometheus with NaN value

---

CHANGELOG.md
lading/src/observer/linux/procfs/memory/smaps.rs

The `smaps` parsing code now correctly handles `pathnames` that are annotated with strings that contain whitespace.
The env var `GLIBC_TUNABLES=glibc.mem.decorate_maps=1` will turn on extra pathname annotations for allocations originating in glibc, which can be very helpful for breaking down RSS. Our parsing code did not correctly handle this, now it should.
```
7514356d1000-7514356d3000 rw-p 00000000 00:00 0                          [anon: glibc: loader malloc]
Size:                  8 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                   8 kB
Pss:                   8 kB
Pss_Dirty:             8 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         8 kB
Referenced:            8 kB
Anonymous:             8 …
```

Fix bug in smaps parsing logic related to pathnames containing whitespace

---

CHANGELOG.md
lading/src/observer/linux.rs
lading/src/observer/linux/procfs.rs

Record smaps data every tenth sample.
These measurements increase capture size and processing time. They're about 1/3 of the metrics in capture files by linecount and by size.

Record smaps less often

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml
lading/src/observer/linux/cgroup/v2.rs
lading/src/observer/linux/cgroup/v2/io.rs
lading/src/observer/linux/cgroup/v2/memory.rs
lading/src/observer/linux/procfs/memory/smaps.rs
lading/src/target_metrics/prometheus.rs

This commit adjusts our Linux observer to record counter data from cgroup v2 as counters. We have found that some of our CPU data does not chart properly because it is recorded in lading as gauges. 
REF SMPTNG-608

Support gauge/counter distinction in Linux observer

---

CHANGELOG.md
Cargo.lock
Cargo.toml
lading_payload/Cargo.toml
lading_payload/src/opentelemetry_log.rs
lading_payload/src/opentelemetry_metric.rs
lading_payload/src/opentelemetry_trace.rs

This is a simple PR to bump the versions of `opentelemetry-proto` and `prost` to their latest versions in order to help reduce duplicate dependencies in a downstream project (`DataDog/saluki`).
The bulk of the PR is compromised by the changes around naming for "scope" fields, which used to be known as "instrumentation library".
Reduce duplicate dependencies in a downstream project.
N/A
N/A

chore: update `opentelemetry-proto` and `prost` to latest version

---

lading/src/observer/linux/procfs/stat.rs

If there are no limits in `cpu.max`, assume all cores instead of just physical cores.  This results in values that match other tools like top (with Irix mode off).
Noticed while evaluating lading.

procfs: Assume all cores for max

---

lading/src/observer/linux/procfs.rs

Currently the process process info (which includes the previous times essential for CPU usage calculation) for the target PID and for some children is erased on every call to `poll` since the `pids` hashset does not include the target PID, and the `retain` call is done inside the inner loop instead of after we gather all the pids.
Noticed while evaluating lading.

procfs: Fix process info retention

---

deny.toml

Allow the unmaintained `paste` crate.
Silence low-signal cargo deny warning.

Allow unmaintained paste crate

---

.github/workflows/check-changelog.yml
CHANGELOG.md

The `tj-actions/changed-files` GitHub action appears to have been compromised. For details, see:
- https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/
- https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
Apparently, using the action can leak CI secrets, so this commit removes our only use of the action and replaces it with an equivalent implementation in shell.
Security.
n/a
Will force-merge once tests pass; given the circumstances, this course of action seems appropriate.

hotfix: remove compromised changed-files action

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
CHANGELOG.md

This addresses some issues with the devcontainer and working in VsCode/Cursor: the rust analyzer was running into some errors around openssl/pkg-config.
With these changes, you should be able to launch VsCode/Cursor in a devcontainer and get appropriate warnings/errors in your IDE as rust-analyzer now runs.
I wasn't seeing errors in my IDE that should have been obvious.
N/A
N/A

feat: fix devcontainer for rust analyzer

---

README.md

Some sections of the readme were out of date. I have also aligned
the formatting of a paragraph in the text, for the sake of being tidy.

Small updates to lading README

---

CHANGELOG.md
lading/src/observer/linux/procfs.rs

This adds a gauge for the number of processes processed in procfs & adds a warning log for when we failed to process processes.
We noticed some spikes in the aggregator numbers that we can't attribute too well with our current observability.
By adding these data points, we'll be better able to understand what's happening when these spikes occur.
N/A
N/A

feat: add procfs process tracking

---

.github/workflows/release.yml
CHANGELOG.md
Cargo.lock
lading/Cargo.toml

This cuts a new release for lading, marking it as version `0.25.7`.
_This also reverts `taiki-e/create-gh-release-action` to a working version._
Wanted a new release so that we could start capturing the new logs/metrics emitted.
https://datadoghq.atlassian.net/browse/SMPTNG-644
N/A

release v0.25.7

---

.github/workflows/container.yml

https://github.com/actions/runner-images/issues/11101

Avoid Ubuntu 20.04 brownout

---

CHANGELOG.md
lading/src/observer/linux/procfs.rs

This commit introduces code into the procfs Sampler such that discovered
children that are not exec'd yet are not polled. We have found that in
rare cases this causes a double-count of the parent's memory, although it's
not accumulated as such by Linux itself.

Ignore forked but not exec'd child processes

---

lading/src/observer/linux/cgroup/v2/cpu.rs

This change has been previously made on the procfs side of the
observer. We now match the cgroup reader.

Adjust cgroup cpu max to use num_cpu::get

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

This commit contains fixes for the observer, using virtual CPU count for both procfs and cgroup CPU calculations as well as ignoring child processes if they are forked but not exec'd when performing memory sums. We will improve the detection mechanism on this later case over time.

Create lading 0.25.8

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
examples/dogstatsd-generation.yaml
examples/lading-logrotatefs.yaml
examples/lading.yaml
integration/sheepdog/src/lib.rs
lading/src/bin/payloadtool.rs
lading/src/config.rs
lading/src/generator/file_gen/logrotate.rs
lading/src/generator/file_gen/logrotate_fs.rs
lading/src/generator/file_gen/traditional.rs
lading/src/generator/grpc.rs
lading/src/generator/http.rs
lading/src/generator/passthru_file.rs
lading/src/generator/splunk_hec.rs
lading/src/generator/tcp.rs
lading/src/generator/udp.rs
lading/src/generator/unix_datagram.rs
lading/src/generator/unix_stream.rs
lading_payload/src/block.rs

This commit updates the byte-unit crate to the latest. There are many
API changes here but the newest version of the crate support math
operations directly on the type without coercion back and forth to
integer values.

Update byte-unit crate to 5.1

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

This release introduces a `container` generator that allows lading to spin and monitor user-provided containers as load for experiments that require scanning containers. Lading is not more strict about interpreting MiB / Mb etc in configurations. Strongly recommend to not mix and match. Lading generators will also no longer allow blocks larger than the throughput setting to pass through, a bug that impacted very low throughput use cases.

Release lading 0.25.9

---

CHANGELOG.md
examples/lading-container.yaml
lading/src/generator/container.rs

Add a new `max_lifetime` parameter to the `container` generator.
This will make `lading` endlessly delete the oldest container and replace it with a newer one.
Some memory leaks inside the agent might happen each time a new container is detected or each time an old container is deleted.
In order to catch them, having a a static set of running containers during the duration of an experiment might not be enough.
We would like to generate a continuous stream of container deletion and container re-creation events.

[CONTINT-4562] Add a parameter to continuously stop and recreate containers

---

lading_payload/proptest-regressions/dogstatsd.txt
lading_payload/src/apache_common.rs
lading_payload/src/ascii.rs
lading_payload/src/block.rs
lading_payload/src/datadog_logs.rs
lading_payload/src/dogstatsd.rs
lading_payload/src/fluent.rs
lading_payload/src/json.rs
lading_payload/src/lib.rs
lading_payload/src/opentelemetry_log.rs
lading_payload/src/opentelemetry_metric.rs
lading_payload/src/opentelemetry_trace.rs
lading_payload/src/splunk_hec.rs
lading_payload/src/statik.rs
lading_payload/src/syslog.rs
lading_payload/src/trace_agent.rs

This commit allows the Serialize trait defined in lading_payload
to mutate itself. This will improve the ergonimics of writing
a serializer that must have some form of memory, without requiring
other serializers to opt into this behavior.
Curiously, this did turn up two problems with dogstatsd: an aliased
function and a framing bug. Both are now corrected. I'm not sure
why this didn't trigger before.
REF SMPTNG-659

Allow lading_payload::Serialize to be mutable

---

.gitignore

This commit ignores the private directory of the claude code CLI assistant,
avoiding the need to negotiate between users of the tool.

Ignore claude code tool private directory

---

lading_payload/src/common.rs
lading_payload/src/common/config.rs
lading_payload/src/common/strings.rs
lading_payload/src/dogstatsd.rs
lading_payload/src/dogstatsd/event.rs
lading_payload/src/dogstatsd/metric.rs
lading_payload/src/dogstatsd/service_check.rs

Migrate OTel/dogstatsd common functions to src/common
This commit is in preparation for more extensive changes to the OTel metrics
payload. I have scooted common configuration and string selection functions up
into the crate common sub-tree.
REF SMPTNG-659

Migrate OTel/dogstatsd common functions to src/common

---

lading_payload/src/common.rs
lading_payload/src/common/config.rs
lading_payload/src/common/strings.rs
lading_payload/src/common/tags.rs
lading_payload/src/dogstatsd/common/tags.rs

The goal of this commit is to take the dogstatsd specific tagset code and
allow it to be generally reused among dogstatsd and otel metrics. I have
demonstrated that dogstatsd is not affected in this PR. I will update the
otel metrics code in a follow-on.
REF SMPTNG-659

Make tagset generation generic

---

CHANGELOG.md
integration/sheepdog/src/lib.rs
lading_payload/Cargo.toml
lading_payload/benches/opentelemetry_metric.rs
lading_payload/src/block.rs
lading_payload/src/lib.rs
lading_payload/src/opentelemetry_metric.rs

This commit adapts the OTel metrics payload internals to use the same
internal mechanism as dogstatsd: a member generator that is capable of
being more fully configured than the previous full-random approach. The
intention here is to support a similar configuration surface among both
payloads.
I have added the ability for users to customize their metric weights,
in a like manner to dogstatsd. In my follow-on commits I will add more
of the dogstatsd surface area and interior implementation, like the
use of templates to avoid reallocation of the same small strings
over and over again.
REF SMPTNG-659

Convert opentelemetry_metric to use MemberGenerator method

---

lading_payload/proptest-regressions/opentelemetry_metric.txt
lading_payload/src/common/config.rs
lading_payload/src/opentelemetry_metric.rs

Generate OTel metrics with context limits
This commit allows users to configure an otel metrics payload that
has a fixed number of 'contexts' to reuse the term from dogstatsd.
This is done by setting a lot of fiddly knobs and the user is
responsible for keeping track of how many unique instances are
possible.
This commit will be chased with some clean-up as I left a lot of
internal duplication in the code. I am also unsure if this generates
sensible load run against a collector, just that it obeys the
protocol by construction.
REF SMPTNG-659

Generate OTel metrics with context limits

---

lading_payload/src/lib.rs
lading_payload/src/opentelemetry_metric.rs
lading_payload/src/opentelemetry_metric/unit.rs

This commit adds a generator for UCUM units and replaces the purely random
strings we were using previously. We use an explicitly enumeraged table which
won't work forever but probably will work for many years until we learn
otherwise. Note that UCUM specifies a number of units do not produce.
REF SMPTNG-659

Generate units according to OTel required spec

---

lading_payload/src/opentelemetry_metric.rs

This commit adds validation cases to the OTel metrics payload
generator. To date we have not done that much to guide users in
getting a good configuration of lading but in this payload we have
sufficient information to be of some help.
REF SMPTNG-659

Add configuration validation for OTel metrics

---

.gitignore

This commit avoids checking in docs-cache. It's useful to have local,
not useful to have checked into the repo.

Ignore .docs-cache in gitignore

---

Cargo.lock
Cargo.toml
integration/ducks/Cargo.toml
integration/ducks/src/main.rs
integration/shared/Cargo.toml

This commit upgrades our tonic depencency to the latest, major change
being the add_service function is now replaced. I believe I got this
wired up right, will wait for CI to tell me so.
REF SMPTNG-659

Upgrade tonic to 0.13

---

CHANGELOG.md
lading/src/generator/grpc.rs
lading/src/generator/http.rs
lading_payload/src/block.rs
lading_payload/src/lib.rs
lading_payload/src/opentelemetry_metric.rs

This commit implements a new piece of telemetry: data points transmitted per
second. This is the equivalent of bytes per second but, when applicable, in
terms of the metric (or other) "data points" transmitted per second. This
approach should be immediately applicable to DogStatsD. This further opens the
door to other block-based metadata.
REF SMPTNG-659

Introduce data_points_transmitted / second in OTel metrics HTTP, GRPC

---

CHANGELOG.md
Cargo.lock
Cargo.toml
examples/lading-otel-metrics.yaml
lading/Cargo.toml
lading/src/blackhole.rs
lading/src/blackhole/otlp.rs
lading/src/blackhole/otlp/grpc.rs
lading/src/blackhole/otlp/http.rs
lading/src/lib.rs
lading_payload/Cargo.toml
lading_payload/src/opentelemetry_metric/templates.rs

The handling of Otlp is specialized enough that having a distinct
blackhole for it makes good sense, especially because we want to be
able to support gRPC request/response and could not with our existing
blackhole. In a subsequent PR I will remove the OtlpMetrics support
in the http blackhole. I believe I also understand how how to make
an otlp_grpc generator.
REF SMPTNG-659

Create Otlp specific blackhole

---

CLAUDE.md

We've found the claude CLI tool is pretty helpful in this project, see
https://github.com/DataDog/lading/pull/1372 for one example. This file is
introduced to follow the recommendations in https://www.anthropic.com/engineering/claude-code-best-practices.
Tooling improvements.

Introduce CLAUDE.md

---

Cargo.lock
lading/Cargo.toml
lading/src/generator/container.rs
lading/src/target.rs

This commit is an attempt to demonstrate the claude CLI tool for
the purposes of mostly mechanical dependency upgrades. This kind
of work is a non-trivial effort sink for lading and other SMP
projects, it'd be swell if a machine could do it.
I find the result here satisfying. I acted as critical reviewer,
claude as implementor.

Update bollard dependency

---

CHANGELOG.md
Cargo.lock
lading/Cargo.toml

This commit is the 0.26.0 lading release. Notable changes include
the measurement of WSS, recorded as `total_wss_bytes`, improvements
to the container generator and a revamp of the OpenTelemetry metrics
payload, inclusion of OTel specific blackholes.

Create lading 0.26.0

---

lading_throttle/src/stable.rs

This commit removes an instance of unsafe code that is not needed,
the MIN const is perfectly safe to use.

Remove unsave NonZero usage

---

lading/src/generator/unix_stream.rs
lading_payload/src/dogstatsd.rs

This commit fixes our prefix length calculation, triggered only when max_bytes
is low. We were removing the size of a `usize` when `u32` was appropriate, as
that is the proper length of the payload prefix.

Fix dogstatsd property test

---

lading/src/bin/payloadtool.rs
lading/src/generator/file_gen/logrotate_fs.rs
lading/src/generator/file_gen/logrotate_fs/model.rs
lading/src/generator/unix_stream.rs
lading_payload/fuzz/fuzz_targets/fixed_cache_creation.rs
lading_payload/fuzz/fuzz_targets/fixed_cache_creation_apache_common.rs
lading_payload/fuzz/fuzz_targets/fixed_cache_creation_ascii.rs
lading_payload/fuzz/fuzz_targets/fixed_cache_creation_datadog_log.rs
lading_payload/fuzz/fuzz_targets/fixed_cache_creation_dogstatsd.rs
lading_payload/fuzz/fuzz_targets/fixed_cache_creation_fluent.rs
lading_payload/fuzz/fuzz_targets/fixed_cache_creation_json.rs
lading_payload/proptest-regressions/dogstatsd.txt
lading_payload/src/block.rs

With the parallel_connection addition to unix_stream we now must solve
the problem of high connection count causing non-trivial cache duplication.
This is done by allowing for a 'handle' on the cache which maintains a separate
index per handle, meaning we do not need to synchronize the cache indexes between
peers and peers are able to reference the singular cache.

Allow block cache to have a 'handle' concept

---

CLAUDE.md
lading/src/observer/linux/procfs.rs

This commit re-introduces the forked but not exec'd heuristic accidentally
removed in PR #1322. This commit re-introduces this heuristic, extracting
it into a function and adding tests to hopefully avoid this situation in
the future.
Once merged we will cut a new version of lading.

Re-introduce forked but not exec'd heuristic

---

CHANGELOG.md
lading/src/generator.rs
lading/src/generator/unix_stream.rs

This commit is a rescue of https://github.com/DataDog/lading/pull/1408 without the accidental merge-in of https://github.com/DataDog/lading/pull/1412. The goal is to reach configuration parity with unix_datagram.

`parallel_connections` for Unix Stream generator

---

CHANGELOG.md
lading/src/observer/linux/procfs.rs
lading/src/observer/linux/procfs/vmstat.rs

Observe `/proc/vmstat` during runs.
This will give us host-level [information](https://docs.kernel.org/admin-guide/mm/transhuge.html#monitoring-usage) about transparent hugepages.

Add `/proc/vmstat` observer

---

CHANGELOG.md
lading/src/bin/lading.rs

Adds better support for lading subcommands and adds a subcommand 'run' that acts as a drop-in replacement for today's "bare" cli usage.
A clean separation of concerns is needed for lading CLI invocations, currently the "main" cli invocation starts all components of lading (observers, generators, target metrics, etc). 
By separating 'run' out into its own subcommand, we pave the way to support lading invocations that only need a subset of the functionality, eg 'lading generate' could _only_ run generators.
Concretely, this is needed for the up-stack PR adding `lading config-check`

Adds structure to support lading subcommands, 'run' is an alias for the current root cmd

---

lading/src/observer/linux/utils/tests/create_process_tree.py

Utility test script was referencing `python` which I don't have on one of my dev machines
manifested in a real funky way:
```
test observer::linux::wss::pfnset::tests::pfn_set ... ok
test target_metrics::prometheus::tests::test_gauge_label_value_with_comma ... FAILED
test target_metrics::prometheus::tests::test_count_zero_labels ... FAILED
test target_metrics::prometheus::tests::test_gauge_edge_case_labels ... FAILED
test target_metrics::prometheus::tests::test_count_one_labels_with_sub_agent_label ... FAILED
test target_metrics::prometheus::tests::test_gauge_mixed_quotes ... FAILED
test target_metrics::prometheus::tests::test_gauge_with_two_series ... FAILED
test target_metrics::prometheus::tests::test_gauge_invalid_value ... FAILED
test …
```

Be explicit about python3, some systems don't have a 'python' binary

---

CHANGELOG.md
CLAUDE.md
integration/sheepdog/src/lib.rs
lading_payload/proptest-regressions/opentelemetry/log/mod.txt
lading_payload/proptest-regressions/opentelemetry_log.txt
lading_payload/src/block.rs
lading_payload/src/lib.rs
lading_payload/src/opentelemetry.rs
lading_payload/src/opentelemetry/common.rs
lading_payload/src/opentelemetry/common/templates.rs
lading_payload/src/opentelemetry/log.rs
lading_payload/src/opentelemetry/log/templates.rs
lading_payload/src/opentelemetry/metric.rs
lading_payload/src/opentelemetry/metric/templates.rs
lading_payload/src/opentelemetry/metric/unit.rs

This commit updates our OTel logs payload to be configurable by the end user. We
allow in a manner similar to metrics for the contexts to be capped, attributes
per level of the message format to be set and seprately from the context
consideration we allow for generation and constraint of total trace-ids.
REF SMPTNG-659

OpenTelemetry logs improvement

---

ci/fuzz
lading_payload/fuzz/Cargo.toml
lading_payload/fuzz/fuzz_targets/fixed_cache_opentelemetry_metrics.rs
lading_payload/fuzz/fuzz_targets/fixed_cache_opentelemetry_metrics_fixed_config.rs
lading_payload/src/opentelemetry/metric.rs

This commit introduces a fuzz target whose goal is to find cases where
to_bytes violates its set budget. My motivation is to add more backing
material for PR #1447.

Introduce fuzz target for OpentelemetryMetrics::to_bytes

---

lading_fuzz/src/lib.rs
lading_payload/fuzz/Cargo.lock

When we introduced lading_fuzz I didn't consider that our clippy lints would
play badly with --build-std. This is now corrected.

Repair compiler error with lading_fuzz intro

---

Cargo.lock
examples/lading-kubernetes.yaml
lading/Cargo.toml
lading/proptest-regressions/generator/kubernetes/state_machine.txt
lading/src/generator/kubernetes.rs
lading/src/generator/kubernetes/resource.rs
lading/src/generator/kubernetes/state_machine.rs

This commit increases the test surface area of the k8s generator in
two ways. Firstly, the implicit state machine is removed to an explict
module and property tested there, leaving IO encumbered code in
kubernetes.rs. In kubernetes.rs we now rely on the lading_throttle
mechanism to maintain the flow of time, avoiding coordinated omission
owing to background tokio scheduling. We further have used the mock
facility of kube-rs to make a small API to assert that the IO code
functions in the happy path as expected.
Having been confused while working on this test code I changed the
configuration to have `max_instance_lifetime_seconds` instead of
`max_lifetime_seconds` and `concurrent_instances` replaces
`number_of_instances`.

Increase testing of the K8s generator

---

Cargo.lock
Cargo.toml
lading/Cargo.toml
lading/src/bin/lading.rs
lading/src/lib.rs

This commit detect and reports via a log message lading's memory
limit. No further actions are taken than this. The goal will be to
feed this information into generators to avoid OOMs based on some user
configurations.

Allow lading to detect its memory limit

---

lading_payload/src/opentelemetry/metric.rs

I'm unsure why I left this log level as error when the low-byte count
failure to make an OTel payload is expected operation.

Adjust error log to debug log

---

CHANGELOG.md
lading/src/common.rs
lading/src/generator/file_gen/logrotate.rs
lading/src/generator/file_gen/traditional.rs
lading/src/generator/grpc.rs
lading/src/generator/passthru_file.rs
lading/src/generator/splunk_hec.rs
lading/src/generator/udp.rs
lading/src/generator/unix_datagram.rs
lading/src/generator/unix_stream.rs
lading_payload/fuzz/fuzz_targets/apache_common_cache_fixed_next_block.rs
lading_payload/fuzz/fuzz_targets/ascii_cache_fixed_next_block.rs
lading_payload/fuzz/fuzz_targets/datadog_log_cache_fixed_next_block.rs
lading_payload/fuzz/fuzz_targets/dogstatsd_cache_fixed_next_block.rs
lading_payload/fuzz/fuzz_targets/fluent_cache_fixed_next_block.rs
lading_payload/fuzz/fuzz_targets/json_cache_fixed_next_block.rs
lading_payload/fuzz/fuzz_targets/opentelemetry_logs_cache_fixed_next_block.rs
lading_payload/fuzz/fuzz_targets/opentelemetry_metrics_cache_fixed_next_block.rs
lading_payload/fuzz/fuzz_targets/syslog5424_cache_fixed_next_block.rs
lading_payload/fuzz/fuzz_targets/trace_agent_cache_fixed_next_block.rs
lading_payload/src/block.rs

This commit removes the old peek interface for the block cache,
converting all generators to use the new `Handle` based approach
excepting logrotate_fs which retains is special-purpose read_at API in
this commit.

Convert remaining generators to new `Handle` block approach

---

lading/Cargo.toml

Cargo-machete is raising an error on the top level Cargo.toml.
Fix CI.
#1534

Fix cargo-machete CI warning
